/**
 * TlsManager — TLS certificate lifecycle for the SecureYeoman gateway.
 *
 * Responsibilities:
 *  - Verify configured cert/key files exist and report expiry status
 *  - Auto-generate self-signed dev certs when `autoGenerate` is true and
 *    no cert files are configured (uses the existing `generateDevCerts()`)
 *  - Expose `ensureCerts()` which returns resolved cert paths (or null when
 *    TLS is disabled) — called by the gateway before startup
 *  - Expose `getCertStatus()` for dashboard / API health display
 *
 * Production deployments must supply their own `certPath`/`keyPath`.
 * Auto-generation is explicitly scoped to development use.
 */

import { existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import * as path from 'node:path';
import { generateDevCerts, isOpenSSLAvailable, type CertPaths } from './cert-gen.js';
import { getLogger, createNoopLogger, type SecureLogger } from '../logging/logger.js';

export interface TlsManagerConfig {
  /** Whether TLS is enabled at all */
  enabled: boolean;
  /** Path to the PEM certificate file */
  certPath?: string;
  /** Path to the PEM private key file */
  keyPath?: string;
  /** Optional CA cert path (enables mTLS when set) */
  caPath?: string;
  /** Auto-generate a self-signed cert when certPath/keyPath are missing */
  autoGenerate: boolean;
  /** Directory where auto-generated certs are stored */
  certDir: string;
}

export interface TlsCertPaths {
  certPath: string;
  keyPath: string;
  caPath?: string;
}

export interface TlsCertStatus {
  enabled: boolean;
  autoGenerated: boolean;
  certPath: string | null;
  keyPath: string | null;
  caPath: string | null;
  expiresAt: number | null;
  daysUntilExpiry: number | null;
  expired: boolean;
  expiryWarning: boolean;
}

const EXPIRY_WARNING_DAYS = 30;

export class TlsManager {
  private readonly config: TlsManagerConfig;
  private generatedPaths: CertPaths | null = null;
  private logger: SecureLogger | null = null;

  constructor(config: TlsManagerConfig) {
    this.config = config;
  }

  /** Whether TLS is enabled. */
  isEnabled(): boolean {
    return this.config.enabled;
  }

  /**
   * Ensure TLS certs are available.
   *
   * - Returns null when TLS is disabled.
   * - Returns the configured paths when cert files already exist.
   * - Auto-generates self-signed certs when `autoGenerate` is true and no
   *   cert files are configured.
   * - Throws when TLS is enabled but certs are unavailable and autoGenerate
   *   is false, or when openssl is not installed.
   */
  async ensureCerts(): Promise<TlsCertPaths | null> {
    if (!this.config.enabled) return null;

    const { certPath, keyPath, caPath, autoGenerate, certDir } = this.config;

    // Explicit paths configured — verify files exist
    if (certPath && keyPath) {
      if (!existsSync(certPath)) {
        throw new Error(`TLS certPath not found: ${certPath}`);
      }
      if (!existsSync(keyPath)) {
        throw new Error(`TLS keyPath not found: ${keyPath}`);
      }
      this.getLogger().info('TLS using configured cert files', { certPath, keyPath });
      return { certPath, keyPath, caPath };
    }

    // Auto-generate
    if (!autoGenerate) {
      throw new Error(
        'TLS is enabled but certPath/keyPath are not configured and autoGenerate is false. ' +
          'Set gateway.tls.certPath + keyPath, or enable gateway.tls.autoGenerate.'
      );
    }

    if (!isOpenSSLAvailable()) {
      throw new Error(
        'TLS autoGenerate is enabled but openssl is not available on PATH. ' +
          'Install openssl or supply pre-generated cert files via gateway.tls.certPath/keyPath.'
      );
    }

    // Reuse already-generated paths for this process lifetime
    if (this.generatedPaths) {
      return {
        certPath: this.generatedPaths.serverCert,
        keyPath: this.generatedPaths.serverKey,
        caPath: this.generatedPaths.caCert,
      };
    }

    // Check if previously generated certs still exist
    const expectedCert = path.join(certDir, 'server-cert.pem');
    const expectedKey = path.join(certDir, 'server-key.pem');
    const expectedCa = path.join(certDir, 'ca-cert.pem');
    if (existsSync(expectedCert) && existsSync(expectedKey)) {
      const expiresAt = this.readCertExpiry(expectedCert);
      if (expiresAt === null || expiresAt > Date.now()) {
        this.getLogger().info('TLS using cached generated certs', { certDir });
        this.generatedPaths = {
          caKey: path.join(certDir, 'ca-key.pem'),
          caCert: expectedCa,
          serverKey: expectedKey,
          serverCert: expectedCert,
        };
        return {
          certPath: expectedCert,
          keyPath: expectedKey,
          caPath: existsSync(expectedCa) ? expectedCa : undefined,
        };
      }
      this.getLogger().info('Auto-generated TLS cert expired — regenerating', { certDir });
    }

    this.getLogger().warn(
      'Generating self-signed TLS certificate — NOT suitable for production',
      { certDir }
    );

    this.generatedPaths = generateDevCerts(certDir);
    return {
      certPath: this.generatedPaths.serverCert,
      keyPath: this.generatedPaths.serverKey,
      caPath: this.generatedPaths.caCert,
    };
  }

  /** Return detailed cert status for dashboard / API display. */
  async getCertStatus(): Promise<TlsCertStatus> {
    const autoGenerated = !this.config.certPath && this.config.autoGenerate;
    const activeCert = this.resolveActiveCertPath();
    const activeKey = this.resolveActiveKeyPath();
    const activeCa = this.resolveActiveCaPath();

    let expiresAt: number | null = null;
    if (activeCert && existsSync(activeCert)) {
      expiresAt = this.readCertExpiry(activeCert);
    }

    const now = Date.now();
    const msPerDay = 86_400_000;
    const daysUntilExpiry = expiresAt !== null ? Math.floor((expiresAt - now) / msPerDay) : null;
    const expired = expiresAt !== null && expiresAt < now;
    const expiryWarning = !expired && daysUntilExpiry !== null && daysUntilExpiry < EXPIRY_WARNING_DAYS;

    return {
      enabled: this.config.enabled,
      autoGenerated,
      certPath: activeCert,
      keyPath: activeKey,
      caPath: activeCa ?? null,
      expiresAt,
      daysUntilExpiry,
      expired,
      expiryWarning,
    };
  }

  // ── Private ─────────────────────────────────────────────────────

  private resolveActiveCertPath(): string | null {
    if (this.config.certPath) return this.config.certPath;
    if (this.generatedPaths) return this.generatedPaths.serverCert;
    const p = path.join(this.config.certDir, 'server-cert.pem');
    return existsSync(p) ? p : null;
  }

  private resolveActiveKeyPath(): string | null {
    if (this.config.keyPath) return this.config.keyPath;
    if (this.generatedPaths) return this.generatedPaths.serverKey;
    const p = path.join(this.config.certDir, 'server-key.pem');
    return existsSync(p) ? p : null;
  }

  private resolveActiveCaPath(): string | undefined {
    if (this.config.caPath) return this.config.caPath;
    if (this.generatedPaths) return this.generatedPaths.caCert;
    const p = path.join(this.config.certDir, 'ca-cert.pem');
    return existsSync(p) ? p : undefined;
  }

  private readCertExpiry(certPath: string): number | null {
    try {
      const out = execFileSync('openssl', ['x509', '-enddate', '-noout', '-in', certPath], {
        stdio: 'pipe',
      }).toString();
      // Output: "notAfter=Jan  1 00:00:00 2026 GMT"
      const match = /notAfter=(.+)/.exec(out);
      if (!match || !match[1]) return null;
      const date = new Date(match[1].trim());
      return isNaN(date.getTime()) ? null : date.getTime();
    } catch {
      return null;
    }
  }

  private getLogger(): SecureLogger {
    if (!this.logger) {
      try {
        this.logger = getLogger().child({ component: 'TlsManager' });
      } catch {
        return createNoopLogger();
      }
    }
    return this.logger;
  }
}
