/**
 * NotificationStorage — Phase 51: Real-Time Infrastructure
 *
 * PostgreSQL-backed storage for in-app notifications.
 * Persists alerts generated by heartbeat, tasks, and security subsystems
 * so they survive process restarts and can be broadcast over WebSocket.
 */

import { PgBaseStorage } from '../storage/pg-base.js';
import { uuidv7 } from '../utils/crypto.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export type NotificationLevel = 'info' | 'warn' | 'error' | 'critical';

export interface Notification {
  id: string;
  type: string;
  title: string;
  body: string;
  level: NotificationLevel;
  source?: string;
  metadata?: Record<string, unknown>;
  readAt: number | null;
  createdAt: number;
}

export interface NewNotification {
  type: string;
  title: string;
  body: string;
  level?: NotificationLevel;
  source?: string;
  metadata?: Record<string, unknown>;
}

export interface ListNotificationsOptions {
  unreadOnly?: boolean;
  limit?: number;
  offset?: number;
}

export interface ListNotificationsResult {
  notifications: Notification[];
  total: number;
}

// ─── Row type ─────────────────────────────────────────────────────────────────

interface NotificationRow {
  id: string;
  type: string;
  title: string;
  body: string;
  level: string;
  source: string | null;
  metadata: Record<string, unknown> | null;
  read_at: string | number | null;
  created_at: string | number;
}

function rowToNotification(row: NotificationRow): Notification {
  return {
    id: row.id,
    type: row.type,
    title: row.title,
    body: row.body,
    level: row.level as NotificationLevel,
    source: row.source ?? undefined,
    metadata: row.metadata ?? undefined,
    readAt:
      row.read_at != null
        ? typeof row.read_at === 'string'
          ? Number(row.read_at)
          : row.read_at
        : null,
    createdAt:
      typeof row.created_at === 'string' ? Number(row.created_at) : row.created_at,
  };
}

// ─── Storage ─────────────────────────────────────────────────────────────────

export class NotificationStorage extends PgBaseStorage {
  async create(n: NewNotification): Promise<Notification> {
    const id = uuidv7();
    const now = Date.now();
    const row = await this.queryOne<NotificationRow>(
      `INSERT INTO notifications (id, type, title, body, level, source, metadata, read_at, created_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, NULL, $8)
       RETURNING *`,
      [
        id,
        n.type,
        n.title,
        n.body,
        n.level ?? 'info',
        n.source ?? null,
        n.metadata ? JSON.stringify(n.metadata) : null,
        now,
      ]
    );
    return rowToNotification(row!);
  }

  async list(opts: ListNotificationsOptions = {}): Promise<ListNotificationsResult> {
    const { unreadOnly = false, limit = 50, offset = 0 } = opts;

    const whereClause = unreadOnly ? 'WHERE read_at IS NULL' : '';

    const [rowsResult, countResult] = await Promise.all([
      this.queryMany<NotificationRow>(
        `SELECT * FROM notifications ${whereClause}
         ORDER BY created_at DESC
         LIMIT $1 OFFSET $2`,
        [limit, offset]
      ),
      this.queryOne<{ count: string }>(
        `SELECT COUNT(*) AS count FROM notifications ${whereClause}`
      ),
    ]);

    return {
      notifications: rowsResult.map(rowToNotification),
      total: Number(countResult?.count ?? 0),
    };
  }

  async markRead(id: string): Promise<boolean> {
    const count = await this.execute(
      `UPDATE notifications SET read_at = $1 WHERE id = $2 AND read_at IS NULL`,
      [Date.now(), id]
    );
    return count > 0;
  }

  async markAllRead(): Promise<number> {
    return this.execute(
      `UPDATE notifications SET read_at = $1 WHERE read_at IS NULL`,
      [Date.now()]
    );
  }

  async delete(id: string): Promise<boolean> {
    const count = await this.execute(`DELETE FROM notifications WHERE id = $1`, [id]);
    return count > 0;
  }

  async unreadCount(): Promise<number> {
    const row = await this.queryOne<{ count: string }>(
      `SELECT COUNT(*) AS count FROM notifications WHERE read_at IS NULL`
    );
    return Number(row?.count ?? 0);
  }

  async deleteOlderThan(maxAgeMs: number): Promise<number> {
    const cutoff = Date.now() - maxAgeMs;
    return this.execute(`DELETE FROM notifications WHERE created_at < $1`, [cutoff]);
  }
}
