/**
 * Shared Types - Main Export
 *
 * Re-exports all shared types for convenient importing
 */

// Task types
export {
  TaskStatus,
  TaskType,
  TaskStatusSchema,
  TaskTypeSchema,
  ResourceUsageSchema,
  TaskErrorSchema,
  SecurityContextSchema,
  TaskSchema,
  TaskCreateSchema,
  TaskUpdateSchema,
  type ResourceUsage,
  type TaskError,
  type SecurityContext,
  type Task,
  type TaskCreate,
  type TaskUpdate,
} from './task.js';

// Security types
export {
  Severity,
  SecurityEventType,
  Role,
  SeveritySchema,
  SecurityEventTypeSchema,
  RoleSchema,
  SecurityEventSchema,
  PermissionSchema,
  RoleDefinitionSchema,
  AuditEntrySchema,
  RateLimitRuleSchema,
  TokenPayloadSchema,
  type SecurityEvent,
  type Permission,
  type RoleDefinition,
  type AuditEntry,
  type RateLimitRule,
  type TokenPayload,
} from './security.js';

// Metrics types
export {
  TaskMetricsSchema,
  ResourceMetricsSchema,
  SecurityMetricsSchema,
  MetricsSnapshotSchema,
  TimeSeriesPointSchema,
  TimeSeriesSchema,
  MetricsQuerySchema,
  type TaskMetrics,
  type ResourceMetrics,
  type SecurityMetrics,
  type MetricsSnapshot,
  type TimeSeriesPoint,
  type TimeSeries,
  type MetricsQuery,
} from './metrics.js';

// AI types
export {
  TokenUsageSchema,
  ToolParameterSchema,
  ToolSchema,
  ToolCallSchema,
  ToolResultSchema,
  AIMessageRoleSchema,
  AIMessageSchema,
  AIRequestSchema,
  StopReasonSchema,
  AIResponseSchema,
  AIStreamChunkSchema,
  AIProviderNameSchema,
  type TokenUsage,
  type ToolParameter,
  type Tool,
  type ToolCall,
  type ToolResult,
  type AIMessageRole,
  type AIMessage,
  type AIRequest,
  type StopReason,
  type AIResponse,
  type AIStreamChunk,
  type AIProviderName,
} from './ai.js';

// Soul types
export {
  PersonalitySchema,
  PersonalityCreateSchema,
  PersonalityUpdateSchema,
  SkillSchema,
  SkillCreateSchema,
  SkillUpdateSchema,
  SkillSourceSchema,
  SkillStatusSchema,
  LearningModeSchema,
  SoulConfigSchema,
  // Skill Actions (ADR 021)
  SkillActionSchema,
  SkillActionTypeSchema,
  CodeActionSchema,
  HttpActionSchema,
  ShellActionSchema,
  // Skill Triggers (ADR 022)
  SkillTriggerSchema,
  TriggerTypeSchema,
  MessageTriggerSchema,
  ToolUseTriggerSchema,
  EventTriggerSchema,
  EventTypeSchema,
  ConditionTriggerSchema,
  MatchModeSchema,
  type Personality,
  type PersonalityCreate,
  type PersonalityUpdate,
  type Skill,
  type SkillCreate,
  type SkillUpdate,
  type SkillSource,
  type SkillStatus,
  type LearningMode,
  type SoulConfig,
  type SkillAction,
  type SkillActionType,
  type CodeAction,
  type HttpAction,
  type ShellAction,
  type SkillTrigger,
  type TriggerType,
  type MessageTrigger,
  type ToolUseTrigger,
  type EventTrigger,
  type EventType,
  type ConditionTrigger,
  type MatchMode,
  MemoryTypeSchema,
  BrainConfigSchema,
  SpiritConfigSchema,
  PassionSchema,
  PassionCreateSchema,
  PassionUpdateSchema,
  InspirationSchema,
  InspirationCreateSchema,
  InspirationUpdateSchema,
  PainSchema,
  PainCreateSchema,
  PainUpdateSchema,
  UserRelationshipSchema,
  UserProfileSchema,
  UserProfileCreateSchema,
  UserProfileUpdateSchema,
  HeartbeatCheckTypeSchema,
  HeartbeatCheckSchema,
  HeartbeatConfigSchema,
  HeartbeatActionConditionSchema,
  HeartbeatActionTypeSchema,
  WebhookActionConfigSchema,
  NotifyActionConfigSchema,
  RememberActionConfigSchema,
  ExecuteActionConfigSchema,
  LLMAnalyzeActionConfigSchema,
  HeartbeatActionTriggerSchema,
  HeartbeatScheduleSchema,
  ExternalBrainProviderSchema,
  ExternalBrainConfigSchema,
  BodyConfigSchema,
  McpFeaturesSchema,
  CreationConfigSchema,
  MessageTypeSchema,
  CommsConfigSchema,
  type UserRelationship,
  type UserProfile,
  type UserProfileCreate,
  type UserProfileUpdate,
  type HeartbeatCheckType,
  type HeartbeatCheck,
  type HeartbeatConfig,
  type HeartbeatActionCondition,
  type HeartbeatActionType,
  type WebhookActionConfig,
  type NotifyActionConfig,
  type RememberActionConfig,
  type ExecuteActionConfig,
  type LLMAnalyzeActionConfig,
  type HeartbeatActionTrigger,
  type HeartbeatSchedule,
  type ExternalBrainProvider,
  type ExternalBrainConfig,
  type MemoryType,
  type BrainConfig,
  type SpiritConfig,
  type Passion,
  type PassionCreate,
  type PassionUpdate,
  type Inspiration,
  type InspirationCreate,
  type InspirationUpdate,
  type Pain,
  type PainCreate,
  type PainUpdate,
  type BodyConfig,
  type McpFeatures,
  type CreationConfig,
  type MessageType,
  type CommsConfig,
} from './soul.js';

// Integration types
export {
  PlatformSchema,
  IntegrationStatusSchema,
  IntegrationConfigSchema,
  IntegrationCreateSchema,
  IntegrationUpdateSchema,
  MessageDirectionSchema,
  MessageAttachmentSchema,
  UnifiedMessageSchema,
  type Platform,
  type IntegrationStatus,
  type IntegrationConfig,
  type IntegrationCreate,
  type IntegrationUpdate,
  type MessageDirection,
  type MessageAttachment,
  type UnifiedMessage,
} from './integration.js';

// MCP types
export {
  McpTransportSchema,
  McpServerConfigSchema,
  McpServerCreateSchema,
  McpToolDefSchema,
  McpResourceDefSchema,
  McpToolManifestSchema,
  McpServiceConfigSchema,
  McpConfigSchema,
  type McpTransport,
  type McpServerConfig,
  type McpServerCreate,
  type McpToolDef,
  type McpResourceDef,
  type McpToolManifest,
  type McpServiceConfig,
  type McpConfig,
} from './mcp.js';

// Reporting types
export {
  ReportFormatSchema,
  AuditReportOptionsSchema,
  AuditReportSchema,
  type ReportFormat,
  type AuditReportOptions,
  type AuditReport,
} from './reporting.js';

// Cost types
export {
  RecommendationPrioritySchema,
  CostRecommendationSchema,
  CostAnalysisSchema,
  type RecommendationPriority,
  type CostRecommendation,
  type CostAnalysis,
} from './cost.js';

// Dashboard types
export {
  WidgetTypeSchema,
  DashboardWidgetSchema,
  CustomDashboardSchema,
  CustomDashboardCreateSchema,
  type WidgetType,
  type DashboardWidget,
  type CustomDashboard,
  type CustomDashboardCreate,
} from './dashboard.js';

// Workspace types
export {
  WorkspaceRoleSchema,
  WorkspaceMemberSchema,
  WorkspaceSchema,
  WorkspaceCreateSchema,
  type WorkspaceRole,
  type WorkspaceMember,
  type Workspace,
  type WorkspaceCreate,
} from './workspace.js';

// Experiment types
export {
  ExperimentStatusSchema,
  VariantSchema,
  ExperimentResultSchema,
  ExperimentSchema,
  ExperimentCreateSchema,
  type ExperimentStatus,
  type Variant,
  type ExperimentResult,
  type Experiment,
  type ExperimentCreate,
} from './experiment.js';

// Marketplace types
export {
  MarketplaceSkillSchema,
  MarketplaceSearchSchema,
  type MarketplaceSkill,
  type MarketplaceSearch,
} from './marketplace.js';

// Config types
export {
  CoreConfigSchema,
  SecurityConfigSchema,
  LoggingConfigSchema,
  MetricsConfigSchema,
  GatewayConfigSchema,
  FallbackModelConfigSchema,
  ModelConfigSchema,
  ConfigSchema,
  PartialConfigSchema,
  type CoreConfig,
  type SecurityConfig,
  type LoggingConfig,
  type MetricsConfig,
  type GatewayConfig,
  type FallbackModelConfig,
  type ModelConfig,
  type Config,
  type PartialConfig,
} from './config.js';
