/**
 * RiskAssessmentManager Tests — Phase 53
 *
 * Pure unit tests — no DB required.
 * Mocks pool.query() per-domain scorer and storage.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { RiskAssessmentManager } from './risk-assessment-manager.js';
import { RiskReportGenerator } from './risk-assessment-report.js';

// ─── Fixtures ────────────────────────────────────────────────────────────────

const NOW = 1_700_000_000_000;
const ASSESS_ID = 'assess-123';

function makeAssessment(overrides: Record<string, unknown> = {}) {
  return {
    id: ASSESS_ID,
    name: 'Test Assessment',
    status: 'completed' as const,
    assessmentTypes: ['security', 'autonomy', 'governance', 'infrastructure', 'external'] as any,
    windowDays: 7,
    compositeScore: 42,
    riskLevel: 'medium' as const,
    domainScores: { security: 30, autonomy: 20, governance: 15, infrastructure: 5, external: 10 },
    findings: [],
    findingsCount: 0,
    createdAt: NOW,
    ...overrides,
  };
}

function makeStorage(overrides: Record<string, unknown> = {}) {
  const base = makeAssessment();
  return {
    create: vi.fn().mockResolvedValue({ ...base, status: 'pending' }),
    get: vi.fn().mockResolvedValue(base),
    list: vi.fn().mockResolvedValue({ items: [base], total: 1 }),
    updateStatus: vi.fn().mockResolvedValue(undefined),
    saveResults: vi.fn().mockResolvedValue({ ...base, status: 'completed' }),
    createFeed: vi.fn().mockResolvedValue({ id: 'feed-1', name: 'Test Feed', sourceType: 'manual', category: 'cyber', enabled: true, recordCount: 0, createdAt: NOW, updatedAt: NOW }),
    listFeeds: vi.fn().mockResolvedValue([]),
    deleteFeed: vi.fn().mockResolvedValue(true),
    ingestFindings: vi.fn().mockResolvedValue({ created: 3, skipped: 1 }),
    listFindings: vi.fn().mockResolvedValue({ items: [], total: 0 }),
    updateFindingStatus: vi.fn().mockResolvedValue({ id: 'finding-1', status: 'acknowledged', category: 'cyber', severity: 'high', title: 'Test', importedAt: NOW }),
    createFinding: vi.fn().mockResolvedValue({ id: 'finding-1', status: 'open', category: 'cyber', severity: 'high', title: 'Test', importedAt: NOW }),
    getFeed: vi.fn().mockResolvedValue(null),
    updateFeed: vi.fn().mockResolvedValue(null),
    ...overrides,
  };
}

function makePool(queryResults: Record<string, unknown>[][] = []) {
  let callIdx = 0;
  return {
    query: vi.fn().mockImplementation(() => {
      const rows = queryResults[callIdx++] ?? [];
      return Promise.resolve({ rows, rowCount: rows.length });
    }),
  };
}

function makeAuditChain(valid = true) {
  return {
    verify: vi.fn().mockResolvedValue({ valid, entriesChecked: 100 }),
  };
}

function makeTlsManager(daysUntilExpiry: number | null = null) {
  return {
    getCertStatus: vi.fn().mockResolvedValue({
      enabled: true,
      autoGenerated: false,
      certPath: '/certs/cert.pem',
      keyPath: '/certs/key.pem',
      caPath: null,
      expiresAt: daysUntilExpiry != null ? Date.now() + daysUntilExpiry * 86400000 : null,
      daysUntilExpiry,
      expired: daysUntilExpiry != null && daysUntilExpiry <= 0,
      expiryWarning: daysUntilExpiry != null && daysUntilExpiry <= 30,
    }),
  };
}

function buildManager(opts: {
  storageOverrides?: Record<string, unknown>;
  poolResults?: Record<string, unknown>[][];
  chainValid?: boolean;
  daysUntilExpiry?: number | null;
} = {}) {
  const storage = makeStorage(opts.storageOverrides ?? {});
  const pool = makePool(opts.poolResults ?? []);
  const auditChain = makeAuditChain(opts.chainValid ?? true);
  const tlsManager = makeTlsManager(opts.daysUntilExpiry ?? null);

  const mgr = new RiskAssessmentManager({
    storage: storage as any,
    pool: pool as any,
    auditChain: auditChain as any,
    tlsManager: tlsManager as any,
  });

  return { mgr, storage, pool, auditChain, tlsManager };
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('RiskAssessmentManager', () => {
  // ── runAssessment ──────────────────────────────────────────────────────────

  describe('runAssessment', () => {
    it('creates assessment, sets running, then saves results', async () => {
      // Run only security domain to keep pool mock order simple
      const { mgr, storage } = buildManager({
        poolResults: [
          [], // security: no audit entries
        ],
      });

      const result = await mgr.runAssessment({
        name: 'Test',
        assessmentTypes: ['security'],
        windowDays: 7,
      });

      expect(storage.create).toHaveBeenCalledOnce();
      expect(storage.updateStatus).toHaveBeenCalledWith(ASSESS_ID, 'running');
      expect(storage.saveResults).toHaveBeenCalledOnce();
      expect(result.status).toBe('completed');
    });

    it('sets status to failed on error', async () => {
      const { mgr, storage } = buildManager({
        storageOverrides: {
          saveResults: vi.fn().mockRejectedValue(new Error('DB error')),
        },
        poolResults: [],
      });

      await mgr.runAssessment({ name: 'Test', assessmentTypes: ['security'], windowDays: 7 });

      expect(storage.updateStatus).toHaveBeenCalledWith(ASSESS_ID, 'failed', 'DB error');
    });
  });

  // ── getAssessment ─────────────────────────────────────────────────────────

  describe('getAssessment', () => {
    it('delegates to storage.get', async () => {
      const { mgr, storage } = buildManager();
      const result = await mgr.getAssessment(ASSESS_ID);
      expect(storage.get).toHaveBeenCalledWith(ASSESS_ID);
      expect(result?.id).toBe(ASSESS_ID);
    });
  });

  // ── listAssessments ───────────────────────────────────────────────────────

  describe('listAssessments', () => {
    it('delegates to storage.list', async () => {
      const { mgr, storage } = buildManager();
      const result = await mgr.listAssessments({ limit: 10 });
      expect(storage.list).toHaveBeenCalledWith({ limit: 10 });
      expect(result.total).toBe(1);
    });
  });

  // ── scoreSecurity ──────────────────────────────────────────────────────────

  describe('scoreSecurity domain', () => {
    it('produces zero score with no events and valid chain', async () => {
      // Only run security domain
      const { mgr, storage } = buildManager({
        poolResults: [
          [], // security scorer: no audit entries
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });

      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.security).toBe(0);
    });

    it('adds score for injection attempts', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // security scorer: single query returns grouped events
          [{ event_type: 'injection_attempt', cnt: '3' }],
        ],
      });

      // Only run security domain to avoid pool mock interleaving
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // 3 injections * 15 = 45, clamped to 40 (injection cap)
      expect(saved.domainScores.security).toBe(40);
      const findings = saved.findings as Array<{ domain: string; severity: string }>;
      expect(findings.some((f) => f.domain === 'security' && f.severity === 'high')).toBe(true);
    });

    it('adds critical finding when audit chain is invalid', async () => {
      const { mgr, storage } = buildManager({
        chainValid: false,
        poolResults: [
          [], // no audit events
          [], // autonomy
          [], // workflow
          [{ count: '0' }], // no audit runs
          [], // governance log
          [{ count: '1' }], // intent
          [], [], [], [], // infra
          [], // external
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // chainPenalty = 25
      expect(saved.domainScores.security).toBe(25);
      const findings = saved.findings as Array<{ domain: string; severity: string }>;
      expect(findings.some((f) => f.severity === 'critical' && f.domain === 'security')).toBe(true);
    });
  });

  // ── scoreAutonomy domain ───────────────────────────────────────────────────

  describe('scoreAutonomy domain', () => {
    it('adds score for L5 items without emergency stop', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // autonomy scorer: soul.skills L5 with no_stop=2
          [{ autonomy_level: 'L5', no_stop: '2' }],
          // autonomy scorer: workflow.definitions (none)
          [],
          // autonomy scorer: completed audit runs
          [{ count: '1' }],
          // autonomy scorer: latest audit run items (empty array = no open items)
          [{ items: '[]' }],
        ],
      });

      // Only run autonomy domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['autonomy'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // l5NoStop=2 * 20 = 40
      expect(saved.domainScores.autonomy).toBe(40);
    });
  });

  // ── scoreGovernance domain ────────────────────────────────────────────────

  describe('scoreGovernance domain', () => {
    it('adds 30 score when no active intent document', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // governance scorer: enforcement_log (no violations)
          [],
          // governance scorer: org_intents (0 active = noIntent = true)
          [{ count: '0' }],
        ],
      });

      // Only run governance domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['governance'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.governance).toBe(30);
      const findings = saved.findings as Array<{ domain: string; severity: string }>;
      expect(findings.some((f) => f.domain === 'governance' && f.severity === 'high')).toBe(true);
    });

    it('adds critical findings for boundary violations', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // governance scorer: enforcement_log with 2 boundary violations
          [{ event_type: 'boundary_violated', cnt: '2' }],
          // governance scorer: org_intents (1 active = not noIntent)
          [{ count: '1' }],
        ],
      });

      // Only run governance domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['governance'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // 2 violations * 20 = 40
      expect(saved.domainScores.governance).toBe(40);
    });
  });

  // ── scoreInfrastructure domain ────────────────────────────────────────────

  describe('scoreInfrastructure domain', () => {
    it('adds critical finding for cert expiry', async () => {
      const { mgr, storage } = buildManager({
        daysUntilExpiry: 15, // < 30 days → certScore = 25
        poolResults: [
          // infra scorer: mcp (none unhealthy)
          [],
          // infra scorer: integrations (none disconnected)
          [],
          // infra scorer: a2a peers (none untrusted online)
          [],
          // infra scorer: heartbeat errors
          [],
        ],
      });

      // Only run infrastructure domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['infrastructure'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.infrastructure).toBe(25);
      const findings = saved.findings as Array<{ domain: string; severity: string }>;
      expect(findings.some((f) => f.domain === 'infrastructure' && f.severity === 'critical')).toBe(true);
    });

    it('scores 0 when infrastructure is clean', async () => {
      const { mgr, storage } = buildManager({
        daysUntilExpiry: 90, // safe
        poolResults: [
          // infra scorer: mcp (count 0 = healthy)
          [{ count: '0' }],
          // infra scorer: integrations (count 0 = ok)
          [{ count: '0' }],
          // infra scorer: a2a peers (count 0 = ok)
          [{ count: '0' }],
          // infra scorer: heartbeat errors
          [{ count: '0' }],
        ],
      });

      // Only run infrastructure domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['infrastructure'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.infrastructure).toBe(0);
    });
  });

  // ── scoreExternal domain ──────────────────────────────────────────────────

  describe('scoreExternal domain', () => {
    it('adds score for critical open external findings', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // external scorer: 2 critical open findings
          [{ severity: 'critical', cnt: '2' }],
        ],
      });

      // Only run external domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['external'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // 2 critical * 25 = 50
      expect(saved.domainScores.external).toBe(50);
    });
  });

  // ── composite score ───────────────────────────────────────────────────────

  describe('composite score', () => {
    it('computes weighted average of domain scores', async () => {
      // Run only security with no events → score 0
      const { mgr, storage } = buildManager({
        poolResults: [
          [], // security: no audit entries
        ],
      });

      await mgr.runAssessment({
        name: 'T',
        assessmentTypes: ['security'],
        windowDays: 7,
      });

      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.compositeScore).toBe(0);
      expect(saved.riskLevel).toBe('low');
    });
  });

  // ── generateReport ────────────────────────────────────────────────────────

  describe('generateReport', () => {
    it('generates JSON report', async () => {
      const { mgr } = buildManager();
      const assessment = makeAssessment({ findings: [] });
      const out = await mgr.generateReport(assessment as any, 'json');
      expect(() => JSON.parse(out)).not.toThrow();
    });

    it('generates Markdown report', async () => {
      const { mgr } = buildManager();
      const assessment = makeAssessment({ findings: [] });
      const out = await mgr.generateReport(assessment as any, 'markdown');
      expect(out).toContain('# Risk Assessment Report');
    });

    it('generates HTML report', async () => {
      const { mgr } = buildManager();
      const assessment = makeAssessment({ findings: [] });
      const out = await mgr.generateReport(assessment as any, 'html');
      expect(out).toContain('<!DOCTYPE html>');
    });

    it('generates CSV report', async () => {
      const { mgr } = buildManager();
      const assessment = makeAssessment({
        findings: [
          {
            id: 'f1',
            domain: 'security',
            severity: 'high',
            title: 'Test',
            description: 'A test finding',
          },
        ],
      });
      const out = await mgr.generateReport(assessment as any, 'csv');
      expect(out).toContain('id,domain,severity');
      expect(out).toContain('Test');
    });
  });

  // ── external feed operations ──────────────────────────────────────────────

  describe('createFeed', () => {
    it('delegates to storage.createFeed', async () => {
      const { mgr, storage } = buildManager();
      const feed = await mgr.createFeed({ name: 'F', sourceType: 'manual', category: 'cyber' });
      expect(storage.createFeed).toHaveBeenCalledOnce();
      expect(feed.name).toBe('Test Feed');
    });
  });

  describe('listFeeds', () => {
    it('delegates to storage.listFeeds', async () => {
      const { mgr, storage } = buildManager();
      await mgr.listFeeds();
      expect(storage.listFeeds).toHaveBeenCalledOnce();
    });
  });

  describe('deleteFeed', () => {
    it('delegates to storage.deleteFeed', async () => {
      const { mgr, storage } = buildManager();
      await mgr.deleteFeed('feed-1');
      expect(storage.deleteFeed).toHaveBeenCalledWith('feed-1');
    });
  });

  describe('ingestFindings', () => {
    it('delegates to storage.ingestFindings', async () => {
      const { mgr, storage } = buildManager();
      const result = await mgr.ingestFindings('feed-1', [{ category: 'cyber', severity: 'high', title: 'T' }] as any);
      expect(storage.ingestFindings).toHaveBeenCalledWith('feed-1', expect.any(Array));
      expect(result.created).toBe(3);
    });
  });

  describe('acknowledgeFinding', () => {
    it('calls storage.updateFindingStatus with acknowledged', async () => {
      const { mgr, storage } = buildManager();
      await mgr.acknowledgeFinding('finding-1', 'alice');
      expect(storage.updateFindingStatus).toHaveBeenCalledWith('finding-1', 'acknowledged', 'alice');
    });
  });

  describe('resolveFinding', () => {
    it('calls storage.updateFindingStatus with resolved', async () => {
      const { mgr, storage } = buildManager();
      await mgr.resolveFinding('finding-1');
      expect(storage.updateFindingStatus).toHaveBeenCalledWith('finding-1', 'resolved');
    });
  });
});

// ─── RiskReportGenerator tests ────────────────────────────────────────────────

describe('RiskReportGenerator', () => {
  const gen = new RiskReportGenerator();

  const assessment = {
    id: 'a1',
    name: 'Test Report',
    status: 'completed' as const,
    assessmentTypes: ['security', 'external'] as any,
    windowDays: 7,
    compositeScore: 65,
    riskLevel: 'high' as const,
    domainScores: { security: 80, external: 30 },
    findings: [
      {
        id: 'f1',
        domain: 'security' as any,
        severity: 'critical' as any,
        title: 'Critical Vuln',
        description: 'Very bad',
        recommendation: 'Fix it',
        affectedResource: 'api',
        evidence: { cve: 'CVE-2024-001' },
      },
    ],
    findingsCount: 1,
    createdAt: 1700000000000,
    completedAt: 1700000001000,
  };

  it('generateJson returns valid JSON', () => {
    const out = gen.generateJson(assessment);
    const parsed = JSON.parse(out);
    expect(parsed.id).toBe('a1');
    expect(parsed.compositeScore).toBe(65);
  });

  it('generateMarkdown includes all sections', () => {
    const out = gen.generateMarkdown(assessment);
    expect(out).toContain('# Risk Assessment Report');
    expect(out).toContain('## Executive Summary');
    expect(out).toContain('## Domain Scores');
    expect(out).toContain('## Critical & High Findings');
    expect(out).toContain('## Recommendations');
    expect(out).toContain('65/100');
  });

  it('generateMarkdown includes finding titles', () => {
    const out = gen.generateMarkdown(assessment);
    expect(out).toContain('Critical Vuln');
  });

  it('generateHtml includes score and level', () => {
    const out = gen.generateHtml(assessment);
    expect(out).toContain('65');
    expect(out).toContain('high');
    expect(out).toContain('Critical Vuln');
  });

  it('generateHtml has proper HTML structure', () => {
    const out = gen.generateHtml(assessment);
    expect(out).toContain('<!DOCTYPE html>');
    expect(out).toContain('<table>');
    expect(out).toContain('Domain Scores');
  });

  it('generateCsv has header and finding row', () => {
    const out = gen.generateCsv(assessment);
    const lines = out.split('\n');
    expect(lines[0]).toBe('id,domain,severity,title,affected_resource,recommendation,evidence_summary');
    expect(lines[1]).toContain('Critical Vuln');
    expect(lines[1]).toContain('critical');
    expect(lines[1]).toContain('security');
  });

  it('generateCsv handles empty findings', () => {
    const out = gen.generateCsv({ ...assessment, findings: [] });
    const lines = out.split('\n').filter(Boolean);
    expect(lines).toHaveLength(1); // header only
  });

  it('generateCsv escapes values with commas', () => {
    const a = {
      ...assessment,
      findings: [
        {
          ...assessment.findings[0],
          title: 'Has, comma',
          description: 'desc',
        },
      ],
    };
    const out = gen.generateCsv(a);
    expect(out).toContain('"Has, comma"');
  });
});
