/**
 * RiskAssessmentManager Tests — Phase 53
 *
 * Pure unit tests — no DB required.
 * Mocks pool.query() per-domain scorer and storage.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { RiskAssessmentManager } from './risk-assessment-manager.js';
import { RiskReportGenerator } from './risk-assessment-report.js';

// ─── Fixtures ────────────────────────────────────────────────────────────────

const NOW = 1_700_000_000_000;
const ASSESS_ID = 'assess-123';

function makeAssessment(overrides: Record<string, unknown> = {}) {
  return {
    id: ASSESS_ID,
    name: 'Test Assessment',
    status: 'completed' as const,
    assessmentTypes: ['security', 'autonomy', 'governance', 'infrastructure', 'external'] as any,
    windowDays: 7,
    compositeScore: 42,
    riskLevel: 'medium' as const,
    domainScores: { security: 30, autonomy: 20, governance: 15, infrastructure: 5, external: 10 },
    findings: [],
    findingsCount: 0,
    createdAt: NOW,
    ...overrides,
  };
}

function makeStorage(overrides: Record<string, unknown> = {}) {
  const base = makeAssessment();
  return {
    create: vi.fn().mockResolvedValue({ ...base, status: 'pending' }),
    get: vi.fn().mockResolvedValue(base),
    list: vi.fn().mockResolvedValue({ items: [base], total: 1 }),
    updateStatus: vi.fn().mockResolvedValue(undefined),
    saveResults: vi.fn().mockResolvedValue({ ...base, status: 'completed' }),
    createFeed: vi.fn().mockResolvedValue({
      id: 'feed-1',
      name: 'Test Feed',
      sourceType: 'manual',
      category: 'cyber',
      enabled: true,
      recordCount: 0,
      createdAt: NOW,
      updatedAt: NOW,
    }),
    listFeeds: vi.fn().mockResolvedValue([]),
    deleteFeed: vi.fn().mockResolvedValue(true),
    ingestFindings: vi.fn().mockResolvedValue({ created: 3, skipped: 1 }),
    listFindings: vi.fn().mockResolvedValue({ items: [], total: 0 }),
    updateFindingStatus: vi.fn().mockResolvedValue({
      id: 'finding-1',
      status: 'acknowledged',
      category: 'cyber',
      severity: 'high',
      title: 'Test',
      importedAt: NOW,
    }),
    createFinding: vi.fn().mockResolvedValue({
      id: 'finding-1',
      status: 'open',
      category: 'cyber',
      severity: 'high',
      title: 'Test',
      importedAt: NOW,
    }),
    getFeed: vi.fn().mockResolvedValue(null),
    updateFeed: vi.fn().mockResolvedValue(null),
    ...overrides,
  };
}

function makePool(queryResults: Record<string, unknown>[][] = []) {
  let callIdx = 0;
  return {
    query: vi.fn().mockImplementation(() => {
      const rows = queryResults[callIdx++] ?? [];
      return Promise.resolve({ rows, rowCount: rows.length });
    }),
  };
}

function makeAuditChain(valid = true) {
  return {
    verify: vi.fn().mockResolvedValue({ valid, entriesChecked: 100 }),
  };
}

function makeTlsManager(daysUntilExpiry: number | null = null) {
  return {
    getCertStatus: vi.fn().mockResolvedValue({
      enabled: true,
      autoGenerated: false,
      certPath: '/certs/cert.pem',
      keyPath: '/certs/key.pem',
      caPath: null,
      expiresAt: daysUntilExpiry != null ? Date.now() + daysUntilExpiry * 86400000 : null,
      daysUntilExpiry,
      expired: daysUntilExpiry != null && daysUntilExpiry <= 0,
      expiryWarning: daysUntilExpiry != null && daysUntilExpiry <= 30,
    }),
  };
}

function buildManager(
  opts: {
    storageOverrides?: Record<string, unknown>;
    poolResults?: Record<string, unknown>[][];
    chainValid?: boolean;
    daysUntilExpiry?: number | null;
  } = {}
) {
  const storage = makeStorage(opts.storageOverrides ?? {});
  const pool = makePool(opts.poolResults ?? []);
  const auditChain = makeAuditChain(opts.chainValid ?? true);
  const tlsManager = makeTlsManager(opts.daysUntilExpiry ?? null);

  const mgr = new RiskAssessmentManager({
    storage: storage as any,
    pool: pool as any,
    auditChain: auditChain as any,
    tlsManager: tlsManager as any,
  });

  return { mgr, storage, pool, auditChain, tlsManager };
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('RiskAssessmentManager', () => {
  // ── runAssessment ──────────────────────────────────────────────────────────

  describe('runAssessment', () => {
    it('creates assessment, sets running, then saves results', async () => {
      // Run only security domain to keep pool mock order simple
      const { mgr, storage } = buildManager({
        poolResults: [
          [], // security: no audit entries
        ],
      });

      const result = await mgr.runAssessment({
        name: 'Test',
        assessmentTypes: ['security'],
        windowDays: 7,
      });

      expect(storage.create).toHaveBeenCalledOnce();
      expect(storage.updateStatus).toHaveBeenCalledWith(ASSESS_ID, 'running');
      expect(storage.saveResults).toHaveBeenCalledOnce();
      expect(result.status).toBe('completed');
    });

    it('sets status to failed on error', async () => {
      const { mgr, storage } = buildManager({
        storageOverrides: {
          saveResults: vi.fn().mockRejectedValue(new Error('DB error')),
        },
        poolResults: [],
      });

      await mgr.runAssessment({ name: 'Test', assessmentTypes: ['security'], windowDays: 7 });

      expect(storage.updateStatus).toHaveBeenCalledWith(ASSESS_ID, 'failed', 'DB error');
    });
  });

  // ── getAssessment ─────────────────────────────────────────────────────────

  describe('getAssessment', () => {
    it('delegates to storage.get', async () => {
      const { mgr, storage } = buildManager();
      const result = await mgr.getAssessment(ASSESS_ID);
      expect(storage.get).toHaveBeenCalledWith(ASSESS_ID);
      expect(result?.id).toBe(ASSESS_ID);
    });
  });

  // ── listAssessments ───────────────────────────────────────────────────────

  describe('listAssessments', () => {
    it('delegates to storage.list', async () => {
      const { mgr, storage } = buildManager();
      const result = await mgr.listAssessments({ limit: 10 });
      expect(storage.list).toHaveBeenCalledWith({ limit: 10 });
      expect(result.total).toBe(1);
    });
  });

  // ── scoreSecurity ──────────────────────────────────────────────────────────

  describe('scoreSecurity domain', () => {
    it('produces zero score with no events and valid chain', async () => {
      // Only run security domain
      const { mgr, storage } = buildManager({
        poolResults: [
          [], // security scorer: no audit entries
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });

      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.security).toBe(0);
    });

    it('adds score for injection attempts', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // security scorer: single query returns grouped events
          [{ event_type: 'injection_attempt', cnt: '3' }],
        ],
      });

      // Only run security domain to avoid pool mock interleaving
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // 3 injections * 15 = 45, clamped to 40 (injection cap)
      expect(saved.domainScores.security).toBe(40);
      const findings = saved.findings as Array<{ domain: string; severity: string }>;
      expect(findings.some((f) => f.domain === 'security' && f.severity === 'high')).toBe(true);
    });

    it('adds critical finding when audit chain is invalid', async () => {
      const { mgr, storage } = buildManager({
        chainValid: false,
        poolResults: [
          [], // no audit events
          [], // autonomy
          [], // workflow
          [{ count: '0' }], // no audit runs
          [], // governance log
          [{ count: '1' }], // intent
          [],
          [],
          [],
          [], // infra
          [], // external
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // chainPenalty = 25
      expect(saved.domainScores.security).toBe(25);
      const findings = saved.findings as Array<{ domain: string; severity: string }>;
      expect(findings.some((f) => f.severity === 'critical' && f.domain === 'security')).toBe(true);
    });
  });

  // ── scoreAutonomy domain ───────────────────────────────────────────────────

  describe('scoreAutonomy domain', () => {
    it('adds score for L5 items without emergency stop', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // autonomy scorer: soul.skills L5 with no_stop=2
          [{ autonomy_level: 'L5', no_stop: '2' }],
          // autonomy scorer: workflow.definitions (none)
          [],
          // autonomy scorer: completed audit runs
          [{ count: '1' }],
          // autonomy scorer: latest audit run items (empty array = no open items)
          [{ items: '[]' }],
        ],
      });

      // Only run autonomy domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['autonomy'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // l5NoStop=2 * 20 = 40
      expect(saved.domainScores.autonomy).toBe(40);
    });
  });

  // ── scoreGovernance domain ────────────────────────────────────────────────

  describe('scoreGovernance domain', () => {
    it('adds 30 score when no active intent document', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // governance scorer: enforcement_log (no violations)
          [],
          // governance scorer: org_intents (0 active = noIntent = true)
          [{ count: '0' }],
        ],
      });

      // Only run governance domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['governance'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.governance).toBe(30);
      const findings = saved.findings as Array<{ domain: string; severity: string }>;
      expect(findings.some((f) => f.domain === 'governance' && f.severity === 'high')).toBe(true);
    });

    it('adds critical findings for boundary violations', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // governance scorer: enforcement_log with 2 boundary violations
          [{ event_type: 'boundary_violated', cnt: '2' }],
          // governance scorer: org_intents (1 active = not noIntent)
          [{ count: '1' }],
        ],
      });

      // Only run governance domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['governance'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // 2 violations * 20 = 40
      expect(saved.domainScores.governance).toBe(40);
    });
  });

  // ── scoreInfrastructure domain ────────────────────────────────────────────

  describe('scoreInfrastructure domain', () => {
    it('adds critical finding for cert expiry', async () => {
      const { mgr, storage } = buildManager({
        daysUntilExpiry: 15, // < 30 days → certScore = 25
        poolResults: [
          // infra scorer: mcp (none unhealthy)
          [],
          // infra scorer: integrations (none disconnected)
          [],
          // infra scorer: a2a peers (none untrusted online)
          [],
          // infra scorer: heartbeat errors
          [],
        ],
      });

      // Only run infrastructure domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['infrastructure'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.infrastructure).toBe(25);
      const findings = saved.findings as Array<{ domain: string; severity: string }>;
      expect(findings.some((f) => f.domain === 'infrastructure' && f.severity === 'critical')).toBe(
        true
      );
    });

    it('scores 0 when infrastructure is clean', async () => {
      const { mgr, storage } = buildManager({
        daysUntilExpiry: 90, // safe
        poolResults: [
          // infra scorer: mcp (count 0 = healthy)
          [{ count: '0' }],
          // infra scorer: integrations (count 0 = ok)
          [{ count: '0' }],
          // infra scorer: a2a peers (count 0 = ok)
          [{ count: '0' }],
          // infra scorer: heartbeat errors
          [{ count: '0' }],
        ],
      });

      // Only run infrastructure domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['infrastructure'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.infrastructure).toBe(0);
    });
  });

  // ── scoreExternal domain ──────────────────────────────────────────────────

  describe('scoreExternal domain', () => {
    it('adds score for critical open external findings', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // external scorer: 2 critical open findings
          [{ severity: 'critical', cnt: '2' }],
        ],
      });

      // Only run external domain
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['external'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // 2 critical * 25 = 50
      expect(saved.domainScores.external).toBe(50);
    });
  });

  // ── composite score ───────────────────────────────────────────────────────

  describe('composite score', () => {
    it('computes weighted average of domain scores', async () => {
      // Run only security with no events → score 0
      const { mgr, storage } = buildManager({
        poolResults: [
          [], // security: no audit entries
        ],
      });

      await mgr.runAssessment({
        name: 'T',
        assessmentTypes: ['security'],
        windowDays: 7,
      });

      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.compositeScore).toBe(0);
      expect(saved.riskLevel).toBe('low');
    });
  });

  // ── generateReport ────────────────────────────────────────────────────────

  describe('generateReport', () => {
    it('generates JSON report', async () => {
      const { mgr } = buildManager();
      const assessment = makeAssessment({ findings: [] });
      const out = await mgr.generateReport(assessment as any, 'json');
      expect(() => JSON.parse(out)).not.toThrow();
    });

    it('generates Markdown report', async () => {
      const { mgr } = buildManager();
      const assessment = makeAssessment({ findings: [] });
      const out = await mgr.generateReport(assessment as any, 'markdown');
      expect(out).toContain('# Risk Assessment Report');
    });

    it('generates HTML report', async () => {
      const { mgr } = buildManager();
      const assessment = makeAssessment({ findings: [] });
      const out = await mgr.generateReport(assessment as any, 'html');
      expect(out).toContain('<!DOCTYPE html>');
    });

    it('generates CSV report', async () => {
      const { mgr } = buildManager();
      const assessment = makeAssessment({
        findings: [
          {
            id: 'f1',
            domain: 'security',
            severity: 'high',
            title: 'Test',
            description: 'A test finding',
          },
        ],
      });
      const out = await mgr.generateReport(assessment as any, 'csv');
      expect(out).toContain('id,domain,severity');
      expect(out).toContain('Test');
    });
  });

  // ── external feed operations ──────────────────────────────────────────────

  describe('createFeed', () => {
    it('delegates to storage.createFeed', async () => {
      const { mgr, storage } = buildManager();
      const feed = await mgr.createFeed({ name: 'F', sourceType: 'manual', category: 'cyber' });
      expect(storage.createFeed).toHaveBeenCalledOnce();
      expect(feed.name).toBe('Test Feed');
    });
  });

  describe('listFeeds', () => {
    it('delegates to storage.listFeeds', async () => {
      const { mgr, storage } = buildManager();
      await mgr.listFeeds();
      expect(storage.listFeeds).toHaveBeenCalledOnce();
    });
  });

  describe('deleteFeed', () => {
    it('delegates to storage.deleteFeed', async () => {
      const { mgr, storage } = buildManager();
      await mgr.deleteFeed('feed-1');
      expect(storage.deleteFeed).toHaveBeenCalledWith('feed-1');
    });
  });

  describe('ingestFindings', () => {
    it('delegates to storage.ingestFindings', async () => {
      const { mgr, storage } = buildManager();
      const result = await mgr.ingestFindings('feed-1', [
        { category: 'cyber', severity: 'high', title: 'T' },
      ] as any);
      expect(storage.ingestFindings).toHaveBeenCalledWith('feed-1', expect.any(Array));
      expect(result.created).toBe(3);
    });
  });

  describe('acknowledgeFinding', () => {
    it('calls storage.updateFindingStatus with acknowledged', async () => {
      const { mgr, storage } = buildManager();
      await mgr.acknowledgeFinding('finding-1', 'alice');
      expect(storage.updateFindingStatus).toHaveBeenCalledWith(
        'finding-1',
        'acknowledged',
        'alice'
      );
    });
  });

  describe('resolveFinding', () => {
    it('calls storage.updateFindingStatus with resolved', async () => {
      const { mgr, storage } = buildManager();
      await mgr.resolveFinding('finding-1');
      expect(storage.updateFindingStatus).toHaveBeenCalledWith('finding-1', 'resolved');
    });
  });

  // ── Additional coverage: listFindings ──────────────────────────────────

  describe('listFindings', () => {
    it('delegates to storage.listFindings with opts', async () => {
      const { mgr, storage } = buildManager();
      await mgr.listFindings({
        feedId: 'feed-1',
        status: 'open',
        severity: 'high',
        limit: 10,
        offset: 5,
      });
      expect(storage.listFindings).toHaveBeenCalledWith({
        feedId: 'feed-1',
        status: 'open',
        severity: 'high',
        limit: 10,
        offset: 5,
      });
    });
  });

  // ── Additional coverage: createFinding ──────────────────────────────────

  describe('createFinding', () => {
    it('delegates to storage.createFinding', async () => {
      const { mgr, storage } = buildManager();
      const result = await mgr.createFinding({
        category: 'cyber',
        severity: 'high',
        title: 'Test',
      } as any);
      expect(storage.createFinding).toHaveBeenCalledOnce();
      expect(result.status).toBe('open');
    });
  });

  // ── Additional coverage: non-Error thrown in runAssessment ──────────────

  describe('runAssessment — non-Error thrown', () => {
    it('converts non-Error to string for failed status', async () => {
      const { mgr, storage } = buildManager({
        storageOverrides: {
          saveResults: vi.fn().mockRejectedValue('string error'),
        },
        poolResults: [],
      });

      await mgr.runAssessment({ name: 'Test', assessmentTypes: ['security'], windowDays: 7 });

      expect(storage.updateStatus).toHaveBeenCalledWith(ASSESS_ID, 'failed', 'string error');
    });
  });

  // ── Additional coverage: runAssessment default assessmentTypes ──────────

  describe('runAssessment — default assessmentTypes', () => {
    it('runs all 5 domains when assessmentTypes not specified', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // security
          [],
          // autonomy skills
          [],
          // autonomy workflows
          [],
          // autonomy audit runs
          [{ count: '0' }],
          // governance log
          [],
          // governance intent
          [{ count: '1' }],
          // infra mcp
          [],
          // infra integrations
          [],
          // infra peers
          [],
          // infra heartbeat
          [],
          // external
          [],
        ],
      });

      await mgr.runAssessment({ name: 'Full', windowDays: 7 });
      expect(storage.saveResults).toHaveBeenCalledOnce();
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // Should have scores for all 5 domains
      expect(Object.keys(saved.domainScores).length).toBeGreaterThanOrEqual(1);
    });
  });

  // ── Additional coverage: department risk snapshot ──────────────────────

  describe('runAssessment — departmentId and getDepartmentRiskManager', () => {
    it('fires department snapshot when departmentId is set and DRM is available', async () => {
      const mockSnapshotFn = vi.fn().mockResolvedValue(undefined);
      const { mgr, storage } = buildManager({ poolResults: [[]] });

      // Replace getDepartmentRiskManager on the instance
      (mgr as any).getDepartmentRiskManager = () => ({
        snapshotDepartmentScore: mockSnapshotFn,
      });

      await mgr.runAssessment({
        name: 'T',
        assessmentTypes: ['security'],
        windowDays: 7,
        departmentId: 'dept-1',
      } as any);

      expect(mockSnapshotFn).toHaveBeenCalledWith('dept-1', ASSESS_ID);
    });

    it('does not throw when snapshotDepartmentScore rejects', async () => {
      const mockSnapshotFn = vi.fn().mockRejectedValue(new Error('snapshot fail'));
      const { mgr } = buildManager({ poolResults: [[]] });

      (mgr as any).getDepartmentRiskManager = () => ({
        snapshotDepartmentScore: mockSnapshotFn,
      });

      // Should not throw
      await expect(
        mgr.runAssessment({
          name: 'T',
          assessmentTypes: ['security'],
          windowDays: 7,
          departmentId: 'dept-1',
        } as any)
      ).resolves.toBeDefined();
    });

    it('skips snapshot when getDepartmentRiskManager returns null', async () => {
      const { mgr } = buildManager({ poolResults: [[]] });

      (mgr as any).getDepartmentRiskManager = () => null;

      await expect(
        mgr.runAssessment({
          name: 'T',
          assessmentTypes: ['security'],
          windowDays: 7,
          departmentId: 'dept-1',
        } as any)
      ).resolves.toBeDefined();
    });

    it('skips snapshot when getDepartmentRiskManager is not set', async () => {
      const { mgr } = buildManager({ poolResults: [[]] });

      (mgr as any).getDepartmentRiskManager = undefined;

      await expect(
        mgr.runAssessment({
          name: 'T',
          assessmentTypes: ['security'],
          windowDays: 7,
          departmentId: 'dept-1',
        } as any)
      ).resolves.toBeDefined();
    });
  });

  // ── Additional coverage: security domain — sandbox, auth, secret findings ─

  describe('scoreSecurity — additional finding branches', () => {
    it('adds sandbox violation critical finding', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [[{ event_type: 'sandbox_violation', cnt: '1' }]],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      const findings = saved.findings as Array<{ title: string; severity: string }>;
      expect(
        findings.some((f) => f.title === 'Sandbox Violations' && f.severity === 'critical')
      ).toBe(true);
    });

    it('adds auth failure finding when count > 10', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [[{ event_type: 'auth_failure', cnt: '15' }]],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      const findings = saved.findings as Array<{ title: string }>;
      expect(findings.some((f) => f.title === 'Elevated Authentication Failures')).toBe(true);
    });

    it('does not add auth failure finding when count <= 10', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [[{ event_type: 'auth_failure', cnt: '5' }]],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      const findings = saved.findings as Array<{ title: string }>;
      expect(findings.some((f) => f.title === 'Elevated Authentication Failures')).toBe(false);
    });

    it('adds secret access finding when count > 5', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [[{ event_type: 'secret_access', cnt: '10' }]],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      const findings = saved.findings as Array<{ title: string }>;
      expect(findings.some((f) => f.title === 'Elevated Secret Access Events')).toBe(true);
    });

    it('handles audit chain verify throwing', async () => {
      const { mgr, storage, auditChain } = buildManager({
        poolResults: [[]],
      });

      (auditChain.verify as any).mockRejectedValue(new Error('chain error'));

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // chainValid = false → 25 penalty
      expect(saved.domainScores.security).toBe(25);
    });
  });

  // ── Additional coverage: autonomy domain — L4 items + open checklist items ─

  describe('scoreAutonomy — additional branches', () => {
    it('scores L4 items without emergency stop', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // skills: L4 no_stop=3
          [{ autonomy_level: 'L4', no_stop: '3' }],
          // workflows: none
          [],
          // audit runs: 1 completed
          [{ count: '1' }],
          // latest audit run with open items
          [{ items: [{ status: 'pending' }, { status: 'fail' }, { status: 'pass' }] }],
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['autonomy'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // l4Score = clamp(3*10, 0, 30) = 30, openItemScore = clamp(2*2, 0, 20) = 4
      expect(saved.domainScores.autonomy).toBe(34);
      const findings = saved.findings as Array<{ title: string }>;
      expect(findings.filter((f) => f.title === 'L4 Item Without Emergency Stop')).toHaveLength(3);
      expect(findings.some((f) => f.title === 'Incomplete Audit Checklist Items')).toBe(true);
    });

    it('handles pool query failure in autonomy (skills/workflows)', async () => {
      const { mgr, storage, pool } = buildManager({ poolResults: [] });
      // Make all queries throw
      (pool.query as any).mockRejectedValue(new Error('table not found'));

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['autonomy'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // All catch blocks → defaults → noAudit = false → score = 0
      expect(saved.domainScores.autonomy).toBe(0);
    });

    it('combines L5 from skills and workflows', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // skills: L5 no_stop=1
          [{ autonomy_level: 'L5', no_stop: '1' }],
          // workflows: L5 no_stop=1
          [{ autonomy_level: 'L5', no_stop: '1' }],
          // audit runs: 0
          [{ count: '0' }],
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['autonomy'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // l5NoStop=2 * 20 = 40, noAudit=true = 20 → total = 60
      expect(saved.domainScores.autonomy).toBe(60);
    });
  });

  // ── Additional coverage: governance — elevated policy block rate ─────

  describe('scoreGovernance — policy block rate finding', () => {
    it('adds finding for elevated policy block rate (> 5/week)', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          // governance log: many policy blocks
          [{ event_type: 'policy_block', cnt: '25' }],
          // org intents active
          [{ count: '1' }],
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['governance'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      const findings = saved.findings as Array<{ title: string }>;
      // 25 blocks / (30/7) ~= 5.83/week > 5 → finding present
      expect(findings.some((f) => f.title === 'Elevated Policy Block Rate')).toBe(true);
    });

    it('handles pool query failure in governance', async () => {
      const { mgr, storage, pool } = buildManager({ poolResults: [] });
      (pool.query as any).mockRejectedValue(new Error('fail'));

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['governance'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.governance).toBe(0);
    });
  });

  // ── Additional coverage: infrastructure — all findings ─────

  describe('scoreInfrastructure — additional findings', () => {
    it('adds findings for unhealthy MCP, failed integrations, untrusted peers, and heartbeat errors', async () => {
      const { mgr, storage } = buildManager({
        daysUntilExpiry: 90,
        poolResults: [
          [{ count: '2' }], // unhealthy MCP
          [{ count: '3' }], // disconnected integrations
          [{ count: '1' }], // untrusted peers
          [{ count: '5' }], // heartbeat errors
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['infrastructure'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      const findings = saved.findings as Array<{ title: string }>;
      expect(findings.some((f) => f.title === 'Unhealthy MCP Servers')).toBe(true);
      expect(findings.some((f) => f.title === 'Disconnected Integrations')).toBe(true);
      expect(findings.some((f) => f.title === 'Online Untrusted A2A Peers')).toBe(true);
    });

    it('handles tlsManager.getCertStatus throwing', async () => {
      const { mgr, storage, tlsManager } = buildManager({
        poolResults: [[], [], [], []],
      });
      (tlsManager.getCertStatus as any).mockRejectedValue(new Error('cert error'));

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['infrastructure'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      // No cert penalty since getCertStatus threw
      expect(saved.domainScores.infrastructure).toBe(0);
    });

    it('skips TLS check when tlsManager is null', async () => {
      const storage = makeStorage();
      const pool = makePool([[], [], [], []]);
      const mgr = new RiskAssessmentManager({
        storage: storage as any,
        pool: pool as any,
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['infrastructure'], windowDays: 7 });
      expect(storage.saveResults).toHaveBeenCalledOnce();
    });

    it('handles TLS cert not enabled (enabled=false)', async () => {
      const { mgr, storage, tlsManager } = buildManager({
        poolResults: [[], [], [], []],
      });
      (tlsManager.getCertStatus as any).mockResolvedValue({ enabled: false });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['infrastructure'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.infrastructure).toBe(0);
    });
  });

  // ── Additional coverage: external — high and medium findings ─────

  describe('scoreExternal — high and medium findings', () => {
    it('adds findings for all severity levels', async () => {
      const { mgr, storage } = buildManager({
        poolResults: [
          [
            { severity: 'critical', cnt: '1' },
            { severity: 'high', cnt: '2' },
            { severity: 'medium', cnt: '3' },
          ],
        ],
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['external'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      const findings = saved.findings as Array<{ title: string }>;
      expect(findings.some((f) => f.title === 'Critical External Findings Open')).toBe(true);
      expect(findings.some((f) => f.title === 'High External Findings Open')).toBe(true);
      expect(findings.some((f) => f.title === 'Medium External Findings Open')).toBe(true);
    });
  });

  // ── Additional coverage: no auditChain → chainValid stays true ─────

  describe('scoreSecurity — no auditChain', () => {
    it('skips chain verification when auditChain is null', async () => {
      const storage = makeStorage();
      const pool = makePool([[]]);
      const mgr = new RiskAssessmentManager({
        storage: storage as any,
        pool: pool as any,
      });

      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 });
      const saved = (storage.saveResults as any).mock.calls[0][1];
      expect(saved.domainScores.security).toBe(0);
    });
  });

  // ── Additional coverage: runAssessment with createdBy ─────

  describe('runAssessment with createdBy', () => {
    it('passes createdBy to storage.create', async () => {
      const { mgr, storage } = buildManager({ poolResults: [[]] });
      await mgr.runAssessment({ name: 'T', assessmentTypes: ['security'], windowDays: 7 }, 'alice');
      expect(storage.create).toHaveBeenCalledWith(expect.any(Object), 'alice');
    });
  });
});

// ─── RiskReportGenerator tests ────────────────────────────────────────────────

describe('RiskReportGenerator', () => {
  const gen = new RiskReportGenerator();

  const assessment = {
    id: 'a1',
    name: 'Test Report',
    status: 'completed' as const,
    assessmentTypes: ['security', 'external'] as any,
    windowDays: 7,
    compositeScore: 65,
    riskLevel: 'high' as const,
    domainScores: { security: 80, external: 30 },
    findings: [
      {
        id: 'f1',
        domain: 'security' as any,
        severity: 'critical' as any,
        title: 'Critical Vuln',
        description: 'Very bad',
        recommendation: 'Fix it',
        affectedResource: 'api',
        evidence: { cve: 'CVE-2024-001' },
      },
    ],
    findingsCount: 1,
    createdAt: 1700000000000,
    completedAt: 1700000001000,
  };

  it('generateJson returns valid JSON', () => {
    const out = gen.generateJson(assessment);
    const parsed = JSON.parse(out);
    expect(parsed.id).toBe('a1');
    expect(parsed.compositeScore).toBe(65);
  });

  it('generateMarkdown includes all sections', () => {
    const out = gen.generateMarkdown(assessment);
    expect(out).toContain('# Risk Assessment Report');
    expect(out).toContain('## Executive Summary');
    expect(out).toContain('## Domain Scores');
    expect(out).toContain('## Critical & High Findings');
    expect(out).toContain('## Recommendations');
    expect(out).toContain('65/100');
  });

  it('generateMarkdown includes finding titles', () => {
    const out = gen.generateMarkdown(assessment);
    expect(out).toContain('Critical Vuln');
  });

  it('generateHtml includes score and level', () => {
    const out = gen.generateHtml(assessment);
    expect(out).toContain('65');
    expect(out).toContain('high');
    expect(out).toContain('Critical Vuln');
  });

  it('generateHtml has proper HTML structure', () => {
    const out = gen.generateHtml(assessment);
    expect(out).toContain('<!DOCTYPE html>');
    expect(out).toContain('<table>');
    expect(out).toContain('Domain Scores');
  });

  it('generateCsv has header and finding row', () => {
    const out = gen.generateCsv(assessment);
    const lines = out.split('\n');
    expect(lines[0]).toBe(
      'id,domain,severity,title,affected_resource,recommendation,evidence_summary'
    );
    expect(lines[1]).toContain('Critical Vuln');
    expect(lines[1]).toContain('critical');
    expect(lines[1]).toContain('security');
  });

  it('generateCsv handles empty findings', () => {
    const out = gen.generateCsv({ ...assessment, findings: [] });
    const lines = out.split('\n').filter(Boolean);
    expect(lines).toHaveLength(1); // header only
  });

  it('generateCsv escapes values with commas', () => {
    const a = {
      ...assessment,
      findings: [
        {
          ...assessment.findings[0],
          title: 'Has, comma',
          description: 'desc',
        },
      ],
    };
    const out = gen.generateCsv(a);
    expect(out).toContain('"Has, comma"');
  });
});
