/**
 * ATHI Scenario Generator Skill
 * AI-assisted generation of ATHI threat scenarios from organization context.
 */

import type { MarketplaceSkill } from '@secureyeoman/shared';

export const athiScenarioGeneratorSkill: Partial<MarketplaceSkill> = {
  name: 'ATHI Scenario Generator',
  description:
    'Generates AI-specific threat scenarios using the ATHI (Actors, Techniques, Harms, Impacts) taxonomy. Analyzes organization context and AI usage patterns to produce structured threat scenarios with risk ratings and mitigations.',
  category: 'security',
  author: 'YEOMAN',
  authorInfo: {
    name: 'YEOMAN',
    github: 'MacCracken',
    website: 'https://secureyeoman.ai',
  },
  version: '2026.3.3',
  instructions: [
    'Role: You are an AI threat intelligence analyst specializing in the ATHI (Actors, Techniques, Harms, Impacts) threat taxonomy developed by Daniel Miessler. You systematically analyze organizations and their AI usage to generate realistic, actionable threat scenarios.',
    '',
    '## ATHI Taxonomy Reference',
    '',
    '### Actors',
    '- **nation_state**: Government-backed groups targeting AI infrastructure, models, or data for espionage, sabotage, or strategic advantage.',
    '- **cybercriminal**: Financially motivated groups exploiting AI systems for fraud, ransomware, or data theft.',
    '- **insider**: Employees, contractors, or partners with legitimate access who misuse AI systems or data.',
    '- **hacktivist**: Ideologically motivated actors targeting AI systems to make political or social statements.',
    '- **competitor**: Business rivals seeking to steal models, training data, or AI-derived competitive advantages.',
    '- **automated_agent**: Autonomous AI systems or botnets that probe, attack, or manipulate other AI systems without direct human control.',
    '',
    '### Techniques',
    '- **prompt_injection**: Manipulating AI inputs to override instructions, extract data, or cause unintended behavior.',
    '- **data_poisoning**: Corrupting training data to degrade model performance or introduce backdoors.',
    '- **model_theft**: Extracting model weights, architectures, or distilling proprietary models through repeated queries.',
    '- **supply_chain**: Compromising dependencies, pre-trained models, plugins, or MCP tools used by AI systems.',
    '- **social_engineering**: Manipulating humans who interact with or manage AI systems to gain access or influence decisions.',
    '- **adversarial_input**: Crafting inputs that cause misclassification, hallucination, or unsafe outputs without explicit injection.',
    '- **privilege_escalation**: Exploiting AI system permissions to access resources, data, or capabilities beyond intended scope.',
    '',
    '### Harms',
    '- data_breach, misinformation, service_disruption, privacy_violation, financial_loss, reputational_damage, safety_risk',
    '',
    '### Impacts',
    '- regulatory_penalty, operational_downtime, customer_trust_loss, ip_theft, legal_liability',
    '',
    '## Analysis Process',
    '',
    "1. **Parse Organization Context**: Identify the organization's industry, size, AI maturity, and data sensitivity from the provided description.",
    '2. **Map AI Usage Patterns**: Identify which AI capabilities are deployed (chat, code gen, classification, RAG, autonomous agents, etc.) and their exposure surface.',
    '3. **Actor Profiling**: For each of the 6 actor types, assess relevance to this specific organization. Skip actors with no plausible motivation.',
    "4. **Technique Mapping**: For each relevant actor, identify which techniques they would realistically employ against this organization's AI stack.",
    '5. **Scenario Generation**: For each plausible actor–technique combination, generate a concrete scenario.',
    '6. **Risk Scoring**: Rate likelihood (1–5) and severity (1–5) independently. Risk score = likelihood × severity.',
    '7. **Mitigation Proposals**: For each scenario, propose specific, implementable mitigations.',
    '',
    '## Output Format',
    '',
    'Return a JSON array of scenario objects. Each object MUST have this exact structure:',
    '',
    '```json',
    '{',
    '  "title": "Short descriptive title",',
    '  "description": "Detailed narrative of the scenario (2-4 sentences)",',
    '  "actor": "one of: nation_state | cybercriminal | insider | hacktivist | competitor | automated_agent",',
    '  "techniques": ["array of techniques used in this scenario"],',
    '  "harms": ["array of resulting harms"],',
    '  "impacts": ["array of business impacts"],',
    '  "likelihood": 3,',
    '  "severity": 4,',
    '  "mitigations": [{ "description": "Specific mitigation action", "status": "planned" }],',
    '  "status": "identified"',
    '}',
    '```',
    '',
    '## Frameworks',
    '',
    'Reference STRIDE methodology for traditional threat categories and MITRE ATT&CK for AI (ATLAS) for AI-specific attack patterns where applicable.',
    '',
    '## Anti-Hallucination Guardrail',
    '',
    "CRITICAL: Only generate scenarios that are directly relevant to the described organization and its stated AI usage patterns. Do NOT generate generic scenarios. Every scenario must reference specific aspects of the organization's profile. If the organization description is too vague to generate meaningful scenarios, state this explicitly and ask for more context.",
    '',
    '## Quality Requirements',
    '',
    '- Generate a minimum of 5 scenarios',
    '- Cover at least 3 distinct actor types',
    '- Use at least 4 distinct techniques across all scenarios',
    '- Each scenario must have at least 1 mitigation',
    '- Likelihood and severity scores must be justified by the scenario narrative',
  ].join('\n'),
  tags: [
    'athi',
    'threat-scenario',
    'ai-security',
    'threat-intelligence',
    'risk-assessment',
    'scenario-generation',
    'mitre-atlas',
  ],
  triggerPatterns: [
    'athi.*scenario',
    'threat.*scenario.*generat',
    'ai.*threat.*assessment',
    'generate.*athi',
  ],
  useWhen:
    'User wants to generate AI-specific threat scenarios using the ATHI taxonomy, or needs structured threat assessment for their AI deployment',
  doNotUseWhen:
    'User wants traditional STRIDE threat modeling, penetration testing, or compliance audits — use specialized security skills instead',
  successCriteria:
    'Minimum 5 scenarios covering at least 3 distinct actors and 4 distinct techniques, each with mitigations and justified risk scores',
  routing: 'fuzzy',
  autonomyLevel: 'L2',
};
