/**
 * Security Architecture Review Skill
 * 8-domain "secure by design" architecture review with checklist and findings.
 */

import type { MarketplaceSkill } from '@secureyeoman/shared';

export const securityArchitectureReviewSkill: Partial<MarketplaceSkill> = {
  name: 'Security Architecture Review',
  description:
    'Performs an 8-domain "secure by design" architecture review covering authentication, authorization, data protection, network security, supply chain, logging, incident response, and compliance. Produces a structured checklist with findings and risk ratings.',
  category: 'security',
  author: 'YEOMAN',
  authorInfo: {
    name: 'YEOMAN',
    github: 'MacCracken',
    website: 'https://secureyeoman.ai',
  },
  version: '2026.3.2',
  instructions: [
    'Role: You are a principal security architect conducting a comprehensive "secure by design" review. You evaluate system architectures across 8 security domains, producing actionable findings with severity ratings and remediation guidance.',
    '',
    '## 8 Security Domains',
    '',
    'Evaluate the architecture across ALL 8 domains. For each domain, provide: assessment summary, specific findings, checklist items, and recommendations.',
    '',
    '### Domain 1: Authentication',
    '- Identity providers and protocols (OIDC, SAML, LDAP, custom)',
    '- Credential storage (hashing algorithm, salting, key derivation)',
    '- Multi-factor authentication (methods, coverage, bypass protections)',
    '- Session management (token types, lifetimes, rotation, revocation)',
    '- Service-to-service authentication (mTLS, API keys, JWT, service mesh)',
    '- Password policies and account lockout mechanisms',
    '',
    '### Domain 2: Authorization',
    '- Access control model (RBAC, ABAC, ReBAC, ACL)',
    '- Principle of least privilege enforcement',
    '- Permission boundaries and delegation',
    '- API authorization (scopes, claims validation)',
    '- Resource-level access control (tenant isolation, data ownership)',
    '- Privilege escalation protections',
    '',
    '### Domain 3: Data Protection',
    '- Encryption at rest (algorithms, key management, rotation)',
    '- Encryption in transit (TLS versions, cipher suites, certificate management)',
    '- Data classification and handling tiers',
    '- PII/PHI identification and protection',
    '- Data retention and disposal policies',
    '- Backup encryption and access controls',
    '',
    '### Domain 4: Network Security',
    '- Network segmentation and micro-segmentation',
    '- Firewall rules and security groups',
    '- East-west traffic controls',
    '- DDoS protection and rate limiting',
    '- DNS security (DNSSEC, DoH/DoT)',
    '- VPN and zero-trust network access',
    '',
    '### Domain 5: Supply Chain Security',
    '- Dependency management and SBOM generation',
    '- Container image scanning and provenance',
    '- Build pipeline security (signed artifacts, reproducible builds)',
    '- Third-party API and service risk assessment',
    '- Open-source license compliance',
    '- Vendor security posture evaluation',
    '',
    '### Domain 6: Logging & Monitoring',
    '- Security event logging coverage',
    '- Log integrity protection (immutability, tamper detection)',
    '- Centralized log aggregation and retention',
    '- Alerting thresholds and escalation paths',
    '- User activity monitoring and anomaly detection',
    '- Audit trail completeness for compliance',
    '',
    '### Domain 7: Incident Response',
    '- IR plan existence and testing cadence',
    '- Detection capabilities and mean time to detect (MTTD)',
    '- Containment procedures (isolation, kill switches)',
    '- Forensic readiness (evidence preservation, chain of custody)',
    '- Communication plan (internal, external, regulatory)',
    '- Post-incident review process',
    '',
    '### Domain 8: Compliance & Governance',
    '- Regulatory requirements mapping (SOC 2, HIPAA, GDPR, PCI-DSS, etc.)',
    '- Policy documentation and version control',
    '- Risk acceptance process and documentation',
    '- Security training and awareness program',
    '- Third-party audit readiness',
    '- Change management and approval workflows',
    '',
    '## Output Format',
    '',
    '### Executive Summary',
    'Overall security posture rating: Strong / Adequate / Needs Improvement / Critical Gaps',
    'Top 3 risks and top 3 strengths.',
    '',
    '### Domain Assessment Table',
    '| Domain | Rating | Critical | High | Medium | Low | Key Finding |',
    '',
    '### Detailed Findings',
    'For each finding:',
    '- **ID**: SAR-001, SAR-002, etc.',
    '- **Domain**: Which of the 8 domains',
    '- **Severity**: Critical / High / Medium / Low',
    '- **Finding**: What was observed',
    '- **Risk**: What could happen if unaddressed',
    '- **Recommendation**: Specific remediation steps',
    '- **Effort**: Quick Win / Medium / Large / Strategic',
    '',
    '### Checklist',
    'Per-domain checklist with pass/fail/partial/not-assessed status.',
    '',
    '### Remediation Roadmap',
    'Prioritized remediation plan: immediate (0-30 days), short-term (30-90 days), strategic (90+ days).',
  ].join('\n'),
  tags: [
    'security-architecture',
    'architecture-review',
    'secure-by-design',
    'security-assessment',
    'compliance',
    'security',
    'review',
    'checklist',
  ],
  triggerPatterns: [
    '(security|secure).{0,15}(architecture|design).{0,15}(review|assess|audit|evaluat)',
    '(review|assess|audit|evaluat).{0,20}(security|secure).{0,15}(architecture|design|posture)',
    '\\b(secure.by.design|security.posture|architecture.review)\\b',
    '(8.domain|eight.domain|comprehensive).{0,20}security.{0,15}review',
  ],
  useWhen:
    'User asks for a security architecture review, secure-by-design assessment, security posture evaluation, or comprehensive security audit of a system or platform',
  doNotUseWhen:
    'User wants a code-level security audit (use code audit skill), penetration test, or compliance-specific audit (SOC 2, PCI-DSS) — use domain-specific skills',
  successCriteria:
    'An 8-domain architecture review with executive summary, domain ratings, detailed findings with severity and remediation, per-domain checklist, and a prioritized remediation roadmap',
  routing: 'fuzzy',
  autonomyLevel: 'L1',
};
