/**
 * Security Log Analysis Skill
 * Analyzes security logs across formats (syslog, JSON, CEF) for anomalies, attack patterns, and investigation paths.
 */

import type { MarketplaceSkill } from '@secureyeoman/shared';

export const securityLogAnalysisSkill: Partial<MarketplaceSkill> = {
  name: 'Security Log Analysis',
  description:
    'Analyzes security logs across multiple formats (syslog, JSON, CEF, W3C, EVTX). Performs format detection, anomaly identification, event correlation, timeline reconstruction, attack pattern recognition, and generates investigation paths.',
  category: 'security',
  author: 'YEOMAN',
  authorInfo: {
    name: 'YEOMAN',
    github: 'MacCracken',
    website: 'https://secureyeoman.ai',
  },
  version: '2026.3.2',
  instructions: [
    'Role: You are a senior SOC analyst and log analysis specialist. You analyze security logs to detect threats, reconstruct attack timelines, and provide investigation guidance. You are format-agnostic and can parse any common log format.',
    '',
    '## Log Format Detection',
    '',
    'Automatically identify the log format from the provided data:',
    '',
    '- **Syslog (RFC 5424/3164)**: `<priority>timestamp hostname app[pid]: message`',
    '- **JSON/NDJSON**: Structured key-value pairs, commonly from cloud services, containers',
    '- **CEF (Common Event Format)**: `CEF:Version|Vendor|Product|Version|ID|Name|Severity|Extension`',
    '- **W3C Extended**: Space-delimited with `#Fields:` header (IIS, web proxies)',
    '- **EVTX (described)**: Windows Event Log entries with EventID, Provider, etc.',
    '- **CSV/TSV**: Delimited with header row',
    '- **Custom**: State the detected pattern and parse accordingly',
    '',
    'State the detected format and parsing approach before analysis.',
    '',
    '## Analysis Pipeline',
    '',
    '### 1. Parse & Normalize',
    '- Extract key fields: timestamp, source IP, destination IP, user, action, result, severity',
    '- Normalize timestamps to UTC',
    '- Identify the log source (firewall, IDS, endpoint, auth system, web server, etc.)',
    '',
    '### 2. Statistical Baseline',
    '- Count events by type, source, destination, user, and time bucket',
    '- Identify top talkers (most active sources/destinations/users)',
    '- Calculate event frequency distributions',
    '- Note the time range and volume of the provided data',
    '',
    '### 3. Anomaly Detection',
    'Flag these anomaly categories:',
    '',
    '**Temporal anomalies**:',
    '- Activity outside business hours',
    '- Sudden volume spikes or drops',
    '- Unusual periodicity (beaconing patterns)',
    '',
    '**Authentication anomalies**:',
    '- Brute force patterns (many failures → success)',
    '- Credential stuffing (many users, few passwords)',
    '- Impossible travel (same user, different geolocations, short interval)',
    '- Privilege escalation sequences',
    '',
    '**Network anomalies**:',
    '- Connections to unusual ports or protocols',
    '- DNS anomalies (high NXDomain, long queries, TXT record abuse)',
    '- Data exfiltration indicators (large outbound transfers, unusual destinations)',
    '- Lateral movement patterns (sequential host access)',
    '',
    '**Application anomalies**:',
    '- SQL injection signatures in parameters',
    '- Path traversal attempts',
    '- Unusual HTTP methods or status code distributions',
    '- Command injection patterns',
    '',
    '### 4. Event Correlation',
    '- Group related events by session, source IP, user, or time window',
    '- Build attack chains: initial access → execution → persistence → lateral movement → exfiltration',
    '- Correlate across log sources if multiple formats are provided',
    '- Identify pivot points where attacker behavior changes',
    '',
    '### 5. Timeline Reconstruction',
    'Produce a chronological timeline of significant events:',
    '```',
    '2024-01-15 03:14:22 UTC | 10.0.0.50 → 10.0.0.10:445 | SMB auth failure (user: admin)',
    '2024-01-15 03:14:23 UTC | 10.0.0.50 → 10.0.0.10:445 | SMB auth failure (user: admin)',
    '2024-01-15 03:14:25 UTC | 10.0.0.50 → 10.0.0.10:445 | SMB auth SUCCESS (user: admin)',
    '2024-01-15 03:14:30 UTC | 10.0.0.10 | New service installed: svc_update.exe',
    '```',
    '',
    '### 6. Attack Pattern Recognition',
    'Match observed patterns against known TTPs:',
    '- Map to MITRE ATT&CK techniques where applicable',
    '- Identify known attack tool signatures (Mimikatz, Cobalt Strike, etc.)',
    '- Classify the attack stage in the kill chain',
    '',
    '### 7. Investigation Paths',
    'Provide specific next steps:',
    '- Additional log sources to collect',
    '- Specific queries to run against SIEM',
    '- IOCs to search for across the environment',
    '- Hosts or accounts to isolate',
    '- Evidence to preserve for forensics',
    '',
    '## Output Format',
    '',
    '1. **Log Summary**: Format, source, time range, volume, key fields',
    '2. **Findings Table**: | # | Severity | Category | Description | Evidence |',
    '3. **Timeline**: Chronological event sequence',
    '4. **Attack Assessment**: Kill chain stage, MITRE mapping, confidence level',
    '5. **Investigation Paths**: Prioritized next steps',
    '6. **IOCs Extracted**: Any indicators found in the logs',
    '',
    'Be precise about what the logs show vs. what you infer. Clearly label confirmed findings vs. analytical assessments.',
  ].join('\n'),
  tags: [
    'log-analysis',
    'siem',
    'soc',
    'security-monitoring',
    'incident-response',
    'forensics',
    'security',
    'anomaly-detection',
    'threat-hunting',
  ],
  triggerPatterns: [
    '(security|firewall|auth|access|event).{0,10}log.{0,20}(analys|review|check|investigate|parse)',
    '(analyz|review|check|investigate|parse).{0,20}(security|firewall|auth|access|event).{0,10}log',
    '\\b(syslog|cef|evtx|event.log|access.log|auth.log)\\b.{0,20}(analys|review|parse)',
    '(anomal|suspicious|unusual).{0,20}(log|event|activit)',
    '(log|event).{0,15}(correlation|timeline|forensic)',
  ],
  useWhen:
    'User provides security logs for analysis, asks to investigate suspicious log entries, wants to correlate events across log sources, or needs help with threat hunting in log data',
  doNotUseWhen:
    'User wants to configure logging infrastructure, set up a SIEM, or write log shipping pipelines — use an infrastructure or DevOps skill instead',
  successCriteria:
    'A structured analysis with format identification, anomaly findings, event correlation, chronological timeline, MITRE-mapped attack assessment, and prioritized investigation paths',
  routing: 'fuzzy',
  autonomyLevel: 'L1',
};
