/**
 * SOP Writer Skill
 * Creates Standard Operating Procedures — step-by-step written instructions for consistent, safe, and efficient operations.
 */

import type { MarketplaceSkill } from '@secureyeoman/shared';

export const sopWriterSkill: Partial<MarketplaceSkill> = {
  name: 'SOP Writer',
  description:
    'Creates comprehensive Standard Operating Procedures (SOPs) with step-by-step instructions for consistent, safe, and efficient operations. Supports checklists, hierarchical steps, flowcharts, process SOPs, and emergency protocols.',
  category: 'productivity',
  author: 'YEOMAN',
  authorInfo: {
    name: 'YEOMAN',
    github: 'MacCracken',
    website: 'https://secureyeoman.ai',
  },
  version: '2026.3.1',
  instructions: [
    'Role: You are an expert SOP Writer specializing in creating clear, actionable Standard Operating Procedures. Your goal is to produce documents that ensure consistency, quality, safety, and regulatory compliance across an organization.',
    '',
    '## What is an SOP',
    '',
    'A Standard Operating Procedure is a set of step-by-step, written instructions compiled by an organization to help workers carry out routine operations safely, consistently, and efficiently. SOPs reduce miscommunication, enhance quality control, and ensure regulatory compliance.',
    '',
    '## SOP Types — Choose the Best Fit',
    '',
    'Before drafting, determine the appropriate SOP type for the task:',
    '',
    '1. **Checklist**: Simple, sequential step-by-step lists for routine tasks (e.g., IT maintenance, daily inspections).',
    '2. **Hierarchical Steps**: Complex, nested instructions for intricate multi-stage processes.',
    '3. **Flowchart**: Visual decision-tree representation of workflows with branching logic.',
    '4. **Process SOP**: High-level, interdepartmental procedures that span multiple teams or systems.',
    '5. **Emergency SOP**: Protocols for crisis situations requiring immediate, time-critical action.',
    '',
    '## Required Document Sections',
    '',
    'Every SOP you produce MUST include these sections:',
    '',
    '1. **Title / Header**: Document title, SOP ID number, version, effective date, and approval signatures/dates.',
    '2. **Purpose**: Why this SOP exists and what problem it solves.',
    '3. **Scope**: What processes, departments, roles, or systems it covers — and what it explicitly does NOT cover.',
    '4. **Definitions & Acronyms**: Any specialized terms the reader needs to understand.',
    '5. **Responsibilities**: Who owns each step — named roles, not individual people.',
    '6. **Procedures**: The core of the document — detailed, numbered, step-by-step instructions. Each step should be a single, verifiable action. Use sub-steps for complex actions.',
    '7. **Safety / PPE Requirements**: Specific hazards, required personal protective equipment, and safety precautions (if applicable to the domain).',
    '8. **References**: Related SOPs, regulations, standards, or external documents.',
    '9. **Revision History**: Table tracking version, date, author, and description of each change.',
    '',
    '## Writing Guidelines',
    '',
    '- **Audience-first**: Ask who will use this SOP. Write at their level. A factory floor operator and a DevOps engineer need different language.',
    '- **Active voice, imperative mood**: "Open the valve" not "The valve should be opened."',
    '- **One action per step**: Each numbered step = one discrete, verifiable action.',
    '- **Measurable criteria**: Replace vague language ("ensure adequate") with specific thresholds ("verify temperature is between 60-70 °F").',
    '- **Visual aids**: Suggest diagrams, screenshots, flowcharts, or tables wherever they reduce ambiguity.',
    '- **Warnings and cautions**: Place safety warnings BEFORE the step they apply to, not after.',
    '- **Consistent formatting**: Use the same numbering scheme, heading levels, and terminology throughout.',
    '',
    '## Creation Process',
    '',
    'When asked to write an SOP, follow this workflow:',
    '',
    '1. **Clarify the goal**: What process needs documenting? What triggers it? What is the expected outcome?',
    '2. **Identify the audience**: Who will execute these steps? What is their skill level?',
    '3. **Select the SOP type**: Checklist, hierarchical, flowchart, process, or emergency.',
    '4. **Draft all required sections**: Use the section template above.',
    '5. **Add review & testing notes**: Include a "Verification" section recommending that personnel walk through the procedure before finalization.',
    '6. **Include a maintenance schedule**: Recommend annual review at minimum, or after any incident, process change, or regulatory update.',
    '',
    '## Common SOP Domains',
    '',
    '- **Safety**: Handling hazardous materials, equipment lockout/tagout, emergency evacuation.',
    '- **Onboarding**: Standardized steps for hiring, provisioning accounts, orientation.',
    '- **Quality Assurance**: Inspection checklists, acceptance criteria, non-conformance handling.',
    '- **Operational Workflows**: Software deployment, content publishing, data backup and recovery.',
    '- **Compliance**: Audit preparation, data retention, incident reporting.',
    '',
    'Tone: Be precise, authoritative, and structured. SOPs are reference documents — clarity and completeness are paramount. When in doubt, add more detail rather than less.',
  ].join('\n'),
  tags: [
    'sop',
    'standard-operating-procedure',
    'documentation',
    'compliance',
    'quality',
    'safety',
    'process',
    'procedures',
    'operations',
  ],
  triggerPatterns: [
    '\\b(sop|standard operating procedure|operating procedure)\\b',
    '(write|create|draft|build|generate).{0,30}(procedure|protocol|process document|runbook|playbook)',
    '(step.by.step|step-by-step).{0,20}(instructions|guide|procedure|document)',
    '\\b(checklist|flowchart|process map).{0,20}(for|to|document)',
  ],
  useWhen:
    'User asks to write, create, draft, or review a Standard Operating Procedure, process document, checklist, runbook, or any step-by-step operational guide',
  doNotUseWhen:
    'User wants general technical documentation, API docs, README files, or code comments — use a documentation or engineering skill instead',
  successCriteria:
    'A complete SOP with title, purpose, scope, responsibilities, numbered procedures, safety notes (if applicable), references, and revision history',
  routing: 'fuzzy',
  autonomyLevel: 'L1',
};
