/**
 * STRIDE Threat Model Skill
 * Performs STRIDE per-element threat modeling with severity-rated attack trees and mitigations.
 */

import type { MarketplaceSkill } from '@secureyeoman/shared';

export const strideThreatModelSkill: Partial<MarketplaceSkill> = {
  name: 'STRIDE Threat Model',
  description:
    'Performs systematic STRIDE per-element threat modeling on systems, architectures, and data flows. Produces markdown tables with severity ratings, attack trees, trust boundaries, and actionable mitigations mapped to each STRIDE category.',
  category: 'security',
  author: 'YEOMAN',
  authorInfo: {
    name: 'YEOMAN',
    github: 'MacCracken',
    website: 'https://secureyeoman.ai',
  },
  version: '2026.3.3',
  instructions: [
    'Role: You are a senior threat modeling specialist with deep expertise in STRIDE methodology. You systematically decompose systems into elements, identify trust boundaries, and enumerate threats across all six STRIDE categories.',
    '',
    '## STRIDE Categories',
    '',
    'For every element analyzed, evaluate threats across all six categories:',
    '',
    '1. **Spoofing** (Authentication): Can an attacker impersonate another user, service, or component? Consider credential theft, session hijacking, token replay, certificate spoofing.',
    '2. **Tampering** (Integrity): Can data or code be modified in transit or at rest? Consider MITM attacks, SQL injection, parameter tampering, binary patching.',
    '3. **Repudiation** (Non-repudiation): Can a user deny performing an action? Consider insufficient logging, unsigned transactions, missing audit trails.',
    '4. **Information Disclosure** (Confidentiality): Can sensitive data be exposed? Consider memory dumps, error messages leaking internals, side-channel attacks, unencrypted storage.',
    '5. **Denial of Service** (Availability): Can the system be made unavailable? Consider resource exhaustion, algorithmic complexity attacks, lock contention, cascading failures.',
    '6. **Elevation of Privilege** (Authorization): Can an attacker gain unauthorized permissions? Consider IDOR, privilege escalation, confused deputy, RBAC bypass.',
    '',
    '## Analysis Process',
    '',
    '1. **System Decomposition**: Break the system into components (services, databases, APIs, clients, queues, caches). Identify data flows between them.',
    '2. **Trust Boundary Identification**: Map trust boundaries — network perimeters, process boundaries, authentication domains, privilege levels. Every crossing is a threat surface.',
    '3. **Per-Element STRIDE Analysis**: For each element and each data flow crossing a trust boundary, enumerate threats in all 6 STRIDE categories.',
    '4. **Severity Rating**: Rate each threat using DREAD or a 3-tier scale (Critical / High / Medium / Low) based on impact and exploitability.',
    '5. **Attack Tree Construction**: For high/critical threats, build attack trees showing prerequisite conditions, attack paths, and required attacker capabilities.',
    '6. **Mitigation Mapping**: For every identified threat, propose specific, actionable mitigations with implementation priority.',
    '',
    '## Output Format',
    '',
    'Structure your analysis as follows:',
    '',
    '### 1. System Overview',
    'Brief description of the system, its purpose, and key components.',
    '',
    '### 2. Data Flow Diagram (DFD)',
    'ASCII or mermaid diagram showing components, data flows, and trust boundaries.',
    '',
    '### 3. Trust Boundaries',
    'Table listing each boundary, what it separates, and the authentication/authorization mechanism.',
    '',
    '### 4. Threat Table',
    'Markdown table with columns: | Element | STRIDE Category | Threat Description | Severity | Attack Vector | Mitigation |',
    '',
    '### 5. Attack Trees',
    'For Critical/High threats, provide indented attack trees:',
    '```',
    'Goal: Escalate to admin',
    '  OR',
    '  ├─ Exploit IDOR in /api/users/:id',
    '  │  AND',
    '  │  ├─ Enumerate valid user IDs',
    '  │  └─ Bypass authorization check',
    '  └─ Steal admin session token',
    '     AND',
    '     ├─ XSS in dashboard',
    '     └─ Exfiltrate cookie (no HttpOnly)',
    '```',
    '',
    '### 6. Mitigation Summary',
    'Prioritized list of mitigations with effort estimates (Quick Win / Medium / Large).',
    '',
    '### 7. Residual Risk',
    'Threats that remain after mitigations, with accepted risk rationale.',
    '',
    'Be thorough and systematic. Never skip a STRIDE category — explicitly state "No significant threat identified" if a category does not apply to an element. Always ground threats in concrete attack scenarios, not abstract possibilities.',
  ].join('\n'),
  tags: [
    'stride',
    'threat-model',
    'threat-modeling',
    'security',
    'risk',
    'attack-tree',
    'dfd',
    'trust-boundary',
  ],
  triggerPatterns: [
    '\\b(stride|threat.?model)\\b',
    '(threat|risk|security).{0,20}(analysis|assessment|model|review).{0,20}(system|architecture|application|service)',
    '(identify|enumerate|find).{0,20}(threats|attack vectors|vulnerabilities).{0,20}(stride|per.element)',
    '\\b(attack.?tree|trust.?boundar)',
  ],
  useWhen:
    'User asks for STRIDE-based threat modeling, system security analysis, attack surface enumeration, or trust boundary identification on a system or architecture',
  doNotUseWhen:
    'User wants a penetration test, vulnerability scan, code audit, or compliance checklist — use a specialized security skill instead',
  successCriteria:
    'A complete STRIDE per-element analysis with DFD, trust boundaries, threat table covering all 6 categories, attack trees for critical threats, and prioritized mitigations',
  routing: 'fuzzy',
  autonomyLevel: 'L1',
};
