import type { SecurityPolicy } from '../api/client';

/**
 * Default mock SecurityPolicy for tests.
 * Spread with overrides: `mockPolicy({ allowSubAgents: true })`
 */
export function mockPolicy(overrides: Partial<SecurityPolicy> = {}): SecurityPolicy {
  return {
    allowSubAgents: false,
    allowA2A: false,
    allowSwarms: false,
    allowExtensions: false,
    allowExecution: true,
    allowProactive: false,
    allowWorkflows: false,
    allowCommunityGitFetch: false,
    allowExperiments: false,
    allowStorybook: false,
    allowMultimodal: false,
    allowDesktopControl: false,
    allowCamera: false,
    allowDynamicTools: false,
    sandboxDynamicTools: true,
    allowAnomalyDetection: false,
    allowSimulation: false,
    sandboxGvisor: false,
    sandboxWasm: false,
    sandboxCredentialProxy: false,
    allowNetworkTools: false,
    allowNetBoxWrite: false,
    allowTwingate: false,
    allowOrgIntent: false,
    allowIntent: false,
    allowIntentEditor: true,
    allowKnowledgeBase: false,
    allowCodeEditor: true,
    allowAdvancedEditor: false,
    allowTrainingExport: false,
    promptGuardMode: 'block',
    responseGuardMode: 'block',
    jailbreakThreshold: 0.5,
    jailbreakAction: 'block',
    strictSystemPromptConfidentiality: false,
    abuseDetectionEnabled: true,
    contentGuardrailsEnabled: true,
    contentGuardrailsPiiMode: 'redact',
    contentGuardrailsToxicityEnabled: true,
    contentGuardrailsToxicityMode: 'block',
    contentGuardrailsToxicityThreshold: 0.7,
    contentGuardrailsBlockList: [],
    contentGuardrailsBlockedTopics: [],
    contentGuardrailsGroundingEnabled: true,
    contentGuardrailsGroundingMode: 'block',
    ...overrides,
  };
}
