import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  Shield,
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Info,
  RefreshCw,
  Eye,
  Loader2,
  FileText,
  Lock,
  LockOpen,
  RefreshCcw,
} from 'lucide-react';
import { fetchTlsStatus } from '../../api/client';
import type { SecurityEvent } from '../../types';

const SEVERITY_ICONS: Record<string, React.ReactNode> = {
  info: <Info className="w-4 h-4 text-info" />,
  warn: <AlertTriangle className="w-4 h-4 text-warning" />,
  error: <XCircle className="w-4 h-4 text-destructive" />,
  critical: <ShieldAlert className="w-4 h-4 text-destructive" />,
};

const SEVERITY_COLORS: Record<string, string> = {
  info: 'border-l-info',
  warn: 'border-l-warning',
  error: 'border-l-destructive',
  critical: 'border-l-destructive bg-destructive/5',
};

function TlsCertStatusCard() {
  const queryClient = useQueryClient();
  const { data: tlsStatus, isLoading } = useQuery({
    queryKey: ['tls-status'],
    queryFn: fetchTlsStatus,
    refetchInterval: 60_000,
  });

  const generateMutation = useMutation({
    mutationFn: () => import('../../api/client').then((m) => m.generateTlsCert()),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: ['tls-status'] });
    },
  });

  if (isLoading) {
    return (
      <div className="card p-4 flex items-center gap-3">
        <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
        <span className="text-sm text-muted-foreground">Loading TLS status…</span>
      </div>
    );
  }

  if (!tlsStatus) return null;

  const statusColor = !tlsStatus.enabled
    ? 'text-muted-foreground'
    : tlsStatus.expired
      ? 'text-destructive'
      : tlsStatus.expiryWarning
        ? 'text-warning'
        : 'text-success';

  const bgColor = !tlsStatus.enabled
    ? 'bg-muted/10'
    : tlsStatus.expired
      ? 'bg-destructive/10'
      : tlsStatus.expiryWarning
        ? 'bg-warning/10'
        : 'bg-success/10';

  return (
    <div className="card p-4">
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-center gap-3 min-w-0">
          <div className={`p-2 rounded-lg ${bgColor} shrink-0`}>
            {tlsStatus.enabled ? (
              <Lock className={`w-5 h-5 ${statusColor}`} />
            ) : (
              <LockOpen className="w-5 h-5 text-muted-foreground" />
            )}
          </div>
          <div className="min-w-0">
            <p className="text-xs text-muted-foreground">TLS / HTTPS</p>
            <p className={`font-semibold ${statusColor}`}>
              {!tlsStatus.enabled
                ? 'Disabled'
                : tlsStatus.expired
                  ? 'Cert expired'
                  : tlsStatus.expiryWarning
                    ? `Expires in ${tlsStatus.daysUntilExpiry}d`
                    : tlsStatus.daysUntilExpiry !== null
                      ? `Valid · ${tlsStatus.daysUntilExpiry}d`
                      : 'Enabled'}
            </p>
            {tlsStatus.autoGenerated && (
              <span className="text-xs text-muted-foreground">(self-signed)</span>
            )}
          </div>
        </div>
        {tlsStatus.enabled && tlsStatus.autoGenerated && (
          <button
            onClick={() => {
              generateMutation.mutate();
            }}
            disabled={generateMutation.isPending}
            title="Regenerate self-signed cert"
            className="btn btn-ghost btn-xs shrink-0 flex items-center gap-1"
          >
            {generateMutation.isPending ? (
              <Loader2 className="w-3 h-3 animate-spin" />
            ) : (
              <RefreshCcw className="w-3 h-3" />
            )}
            Regen
          </button>
        )}
      </div>
    </div>
  );
}

export function SecurityOverviewTab({
  events,
  criticalCount,
  warningCount,
  verifying,
  verificationResult,
  onVerify,
  onAcknowledge,
  onAcknowledgeAll,
  onViewAuditLog,
}: {
  events: SecurityEvent[];
  criticalCount: number;
  warningCount: number;
  verifying: boolean;
  verificationResult: { valid: boolean; entriesChecked: number; error?: string } | null;
  onVerify: () => void;
  onAcknowledge: (id: string) => void;
  onAcknowledgeAll: () => void;
  onViewAuditLog: () => void;
}) {
  return (
    <div className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-destructive/10">
              <ShieldAlert className="w-5 h-5 text-destructive" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Critical</p>
              <p className="text-2xl font-bold">{criticalCount}</p>
            </div>
          </div>
        </div>
        <div className="card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-warning/10">
              <AlertTriangle className="w-5 h-5 text-warning" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Warnings</p>
              <p className="text-2xl font-bold">{warningCount}</p>
            </div>
          </div>
        </div>
        <div className="card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-success/10">
              <ShieldCheck className="w-5 h-5 text-success" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Audit Status</p>
              <div className="flex items-center gap-2">
                <button
                  onClick={onVerify}
                  disabled={verifying}
                  className="text-sm font-medium text-primary hover:underline flex items-center gap-1"
                >
                  {verifying ? (
                    <Loader2 className="w-3 h-3 animate-spin" />
                  ) : (
                    <RefreshCw className="w-3 h-3" />
                  )}
                  {verificationResult
                    ? verificationResult.valid
                      ? 'Verified'
                      : 'Failed'
                    : 'Verify'}
                </button>
                <button
                  onClick={onViewAuditLog}
                  className="text-xs text-muted-foreground hover:text-foreground flex items-center gap-1"
                >
                  <Eye className="w-3 h-3" />
                  View Log
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="card p-4">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10">
              <Shield className="w-5 h-5 text-primary" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Total Events</p>
              <p className="text-2xl font-bold">{events.length}</p>
            </div>
          </div>
        </div>
        <TlsCertStatusCard />
      </div>

      {verificationResult && (
        <div
          className={`card p-4 border-l-4 ${
            verificationResult.valid
              ? 'border-l-success bg-success/5'
              : 'border-l-destructive bg-destructive/5'
          }`}
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              {verificationResult.valid ? (
                <CheckCircle className="w-5 h-5 text-success" />
              ) : (
                <XCircle className="w-5 h-5 text-destructive" />
              )}
              <span className="font-medium">
                {verificationResult.valid
                  ? `Audit chain verified (${verificationResult.entriesChecked} entries)`
                  : verificationResult.error || 'Verification failed'}
              </span>
            </div>
            <button
              onClick={onViewAuditLog}
              className="text-sm text-primary hover:underline flex items-center gap-1"
            >
              <FileText className="w-4 h-4" />
              View Audit Log
            </button>
          </div>
        </div>
      )}

      <div className="flex items-center justify-between">
        <h3 className="font-semibold">Recent Security Events</h3>
        <button
          onClick={onAcknowledgeAll}
          className="text-sm text-muted-foreground hover:text-foreground"
        >
          Acknowledge all
        </button>
      </div>

      {events.length === 0 ? (
        <div className="card p-8 text-center">
          <ShieldCheck className="w-12 h-12 mx-auto text-success mb-3" />
          <p className="text-muted-foreground">No security events</p>
        </div>
      ) : (
        <div className="space-y-2">
          {events.map((event) => (
            <div
              key={event.id}
              className={`card p-4 border-l-4 ${SEVERITY_COLORS[event.severity] || 'border-l-info'}`}
            >
              <div className="flex items-start justify-between gap-4">
                <div className="flex items-start gap-3">
                  {SEVERITY_ICONS[event.severity] || <Info className="w-4 h-4" />}
                  <div>
                    <p className="font-medium text-sm">{event.message}</p>
                    <p className="text-xs text-muted-foreground mt-1">{event.type}</p>
                    <p className="text-xs text-muted-foreground mt-1">
                      {new Date(event.timestamp).toLocaleString()}
                    </p>
                  </div>
                </div>
                <button
                  onClick={() => {
                    onAcknowledge(event.id);
                  }}
                  className="text-muted-foreground hover:text-foreground"
                  title="Acknowledge"
                >
                  <Eye className="w-4 h-4" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
